import { html, tri, type Tri } from "./seed-helpers";

export type ProgrammeSeed = {
  slug: string;
  category: "WELFARE" | "EMERGENCY" | "MEMBER_SUPPORT" | "COMMUNITY";
  icon: string;
  coverImage: string;
  benefitAmount?: number;
  sortOrder: number;
  title: Tri;
  summary: Tri;
  eligibility: Tri;
  body: Tri;
};

export const PROGRAMMES: ProgrammeSeed[] = [
  {
    slug: "death-donation-scheme",
    category: "WELFARE",
    icon: "HeartHandshake",
    coverImage: "/media/dry-rations.svg",
    benefitAmount: 150000,
    sortOrder: 1,
    title: tri("Death Donation Scheme", "මරණ ආධාර යෝජනා ක්‍රමය", "மரண நிவாரண திட்டம்"),
    summary: tri(
      "An immediate cash grant to the family of a deceased member or registered dependant, paid within 48 hours of notification.",
      "මියගිය සාමාජිකයෙකුගේ හෝ ලියාපදිංචි යැපෙන්නෙකුගේ පවුලට, දැනුම් දීමෙන් පැය 48ක් ඇතුළත ගෙවන ක්ෂණික මුදල් ආධාරයක්.",
      "மரணமான உறுப்பினரின் அல்லது பதிவு செய்யப்பட்ட சார்பினரின் குடும்பத்திற்கு, அறிவித்த 48 மணி நேரத்தில் வழங்கப்படும் உடனடி பண உதவி.",
    ),
    eligibility: tri(
      "Members in good standing for at least six months, with subscriptions paid up to date.",
      "අවම මාස හයක් සාමාජිකත්වය පවත්වා, දායක මුදල් යාවත්කාලීනව ගෙවා ඇති සාමාජිකයින්.",
      "குறைந்தது ஆறு மாதங்கள் உறுப்புரிமை கொண்ட, சந்தா நிலுவையின்றி செலுத்திய உறுப்பினர்கள்.",
    ),
    body: {
      en: html([
        "The death donation is the oldest and most used scheme in the association. It exists for a simple reason: funeral costs arrive suddenly, and no grieving family should have to borrow at high interest in the first week of a bereavement.",
        "## What is paid",
        [
          "<strong>Rs. 150,000</strong> on the death of a member",
          "<strong>Rs. 75,000</strong> on the death of a registered spouse",
          "<strong>Rs. 40,000</strong> on the death of a registered child or dependent parent",
        ],
        "## How the payment is made",
        "A member of the welfare sub-committee visits the family within 24 hours of notification. The grant is handed over as a cheque or transferred to the nominated bank account, with a signed voucher recorded in the ledger that is published in the annual report.",
        "## Notifying the association",
        "Call the welfare hotline at any hour. The hotline is answered outside office hours specifically for this scheme. A death certificate or hospital notification is required to release the payment, but the visit and paperwork begin before that document arrives.",
        "> In 2025 the scheme paid out 41 grants totalling Rs. 4.9 million, with an average time from notification to payment of 31 hours.",
      ]),
      si: html([
        "මරණ ආධාරය සමිතියේ පැරණිතම සහ වැඩිපුරම භාවිත වන යෝජනා ක්‍රමයයි. එය පවතින්නේ සරල හේතුවක් නිසාය: අවමංගල්‍ය වියදම් හදිසියේ පැමිණේ, සහ ශෝකයට පත් කිසිදු පවුලක් මරණයේ පළමු සතියේ ඉහළ පොලියට ණය ගත යුතු නැත.",
        "## ගෙවනු ලබන මුදල",
        [
          "සාමාජිකයෙකුගේ මරණයකදී <strong>රු. 150,000</strong>",
          "ලියාපදිංචි කලත්‍රයෙකුගේ මරණයකදී <strong>රු. 75,000</strong>",
          "ලියාපදිංචි දරුවෙකුගේ හෝ යැපෙන දෙමාපියෙකුගේ මරණයකදී <strong>රු. 40,000</strong>",
        ],
        "## ගෙවීම සිදු කරන ආකාරය",
        "දැනුම් දීමෙන් පැය 24ක් ඇතුළත සුබසාධක උපකමිටුවේ සාමාජිකයෙකු පවුල බැලීමට යයි. ආධාරය චෙක්පතක් ලෙස හෝ නම් කරන ලද බැංකු ගිණුමට මාරු කරනු ලබන අතර, අත්සන් කළ වවුචරයක් වාර්ෂික වාර්තාවේ ප්‍රකාශයට පත් කරන ලෙජරයේ සටහන් වේ.",
        "## සමිතියට දැනුම් දීම",
        "කවර වේලාවකදීත් සුබසාධක හදිසි ඇමතුම් අංකයට කතා කරන්න. මෙම යෝජනා ක්‍රමය සඳහාම කාර්යාල වේලාවෙන් පිටතද එම අංකයට පිළිතුරු දෙනු ලැබේ. ගෙවීම නිදහස් කිරීමට මරණ සහතිකයක් හෝ රෝහල් දැනුම්දීමක් අවශ්‍ය වේ, නමුත් එම ලේඛනය පැමිණීමට පෙර සංචාරය සහ ලේඛන කටයුතු ආරම්භ වේ.",
        "> 2025 වර්ෂයේ මෙම යෝජනා ක්‍රමය මගින් රු. මිලියන 4.9 ක් වටිනා ආධාර 41 ක් ගෙවා ඇති අතර, දැනුම් දීමේ සිට ගෙවීම දක්වා සාමාන්‍ය කාලය පැය 31 කි.",
      ]),
      ta: html([
        "மரண நிவாரணம் சங்கத்தின் மிகப் பழமையான, அதிகம் பயன்படுத்தப்படும் திட்டமாகும். இது ஒரு எளிய காரணத்திற்காக உள்ளது: இறுதிச் சடங்குச் செலவுகள் திடீரென வருகின்றன, துக்கத்தில் உள்ள எந்தக் குடும்பமும் முதல் வாரத்தில் அதிக வட்டிக்குக் கடன் பெற வேண்டியதில்லை.",
        "## வழங்கப்படும் தொகை",
        [
          "உறுப்பினரின் மரணத்தில் <strong>ரூ. 150,000</strong>",
          "பதிவு செய்யப்பட்ட வாழ்க்கைத் துணையின் மரணத்தில் <strong>ரூ. 75,000</strong>",
          "பதிவு செய்யப்பட்ட பிள்ளை அல்லது சார்பு பெற்றோரின் மரணத்தில் <strong>ரூ. 40,000</strong>",
        ],
        "## கட்டணம் செலுத்தப்படும் விதம்",
        "அறிவித்த 24 மணி நேரத்தில் நலன்புரி உபகுழு உறுப்பினர் ஒருவர் குடும்பத்தைச் சந்திக்கிறார். நிவாரணம் காசோலையாக அல்லது குறிப்பிட்ட வங்கிக் கணக்கிற்கு மாற்றப்படும், கையொப்பமிட்ட வவுச்சர் வருடாந்த அறிக்கையில் வெளியிடப்படும் பேரேட்டில் பதிவாகும்.",
        "## சங்கத்திற்கு அறிவித்தல்",
        "எந்த நேரத்திலும் நலன்புரி அவசர இலக்கத்தை அழையுங்கள். இந்தத் திட்டத்திற்காகவே அலுவலக நேரத்திற்கு வெளியேயும் அந்த இலக்கத்திற்குப் பதிலளிக்கப்படும். கட்டணத்தை விடுவிக்க மரணச் சான்றிதழ் அல்லது வைத்தியசாலை அறிவிப்பு தேவை, ஆனால் அந்த ஆவணம் வருவதற்கு முன்பே வருகையும் ஆவணப் பணிகளும் தொடங்கும்.",
        "> 2025 இல் இந்தத் திட்டம் ரூ. 4.9 மில்லியன் மதிப்புள்ள 41 நிவாரணங்களை வழங்கியது, அறிவித்ததில் இருந்து கட்டணம் வரையான சராசரி நேரம் 31 மணி நேரம்.",
      ]),
    },
  },
  {
    slug: "medical-assistance-fund",
    category: "WELFARE",
    icon: "Stethoscope",
    coverImage: "/media/eye-clinic.svg",
    benefitAmount: 75000,
    sortOrder: 2,
    title: tri("Medical Assistance Fund", "වෛද්‍ය ආධාර අරමුදල", "மருத்துவ உதவி நிதியம்"),
    summary: tri(
      "Support towards surgery, hospitalisation, dialysis and long-term medication for members and their dependants.",
      "සාමාජිකයින් සහ ඔවුන්ගේ යැපෙන්නන් සඳහා ශල්‍යකර්ම, රෝහල්ගත වීම, ඩයලිසිස් සහ දිගුකාලීන ඖෂධ සඳහා සහාය.",
      "உறுப்பினர்களுக்கும் அவர்களது சார்பினர்களுக்கும் அறுவைச் சிகிச்சை, வைத்தியசாலை அனுமதி, சிறுநீரகக் கழுவல் மற்றும் நீண்டகால மருந்துகளுக்கான ஆதரவு.",
    ),
    eligibility: tri(
      "Members with twelve months of continuous membership. Claims must be supported by a consultant's report.",
      "අඛණ්ඩ මාස දොළහක සාමාජිකත්වයක් ඇති සාමාජිකයින්. ඉල්ලීම් විශේෂඥ වෛද්‍ය වාර්තාවකින් අනුබල දිය යුතුය.",
      "தொடர்ச்சியாக பன்னிரண்டு மாதங்கள் உறுப்புரிமை கொண்ட உறுப்பினர்கள். கோரிக்கைகள் நிபுணர் அறிக்கையால் ஆதரிக்கப்பட வேண்டும்.",
    ),
    body: {
      en: html([
        "State hospitals in Sri Lanka provide free treatment, but families still face the cost of scans, imported medicines, travel to Colombo and lost income while a breadwinner recovers. This fund covers exactly those gaps.",
        "## Ceilings by category",
        [
          "Major surgery — up to <strong>Rs. 75,000</strong> per member per year",
          "Dialysis support — <strong>Rs. 8,000</strong> per month for up to twelve months",
          "Cancer treatment travel and accommodation — up to <strong>Rs. 45,000</strong>",
          "Chronic medication (diabetes, cardiac, renal) — up to <strong>Rs. 24,000</strong> per year",
        ],
        "## Making a claim",
        "Open a welfare claim from your member dashboard, or submit form HLA/W-04 with the consultant's report and receipts. Claims are reviewed at the fortnightly welfare sub-committee meeting. Urgent cases are decided by the chairperson and treasurer jointly within 24 hours and ratified at the next meeting.",
        "## What is not covered",
        "Cosmetic procedures, treatment already reimbursed by an insurer or employer, and private-hospital charges where a state facility was available. The sub-committee may make exceptions in documented emergencies.",
      ]),
      si: html([
        "ශ්‍රී ලංකාවේ රජයේ රෝහල් නොමිලේ ප්‍රතිකාර සපයන නමුත්, පවුල්වලට තවමත් ස්කෑන්, ආනයනික ඖෂධ, කොළඹ යාමේ වියදම සහ ආදායම් ලබන්නා සුවය ලබන කාලයේ අහිමි වන ආදායම මුහුණ දිය යුතුය. මෙම අරමුදල හරියටම එම හිඩැස් ආවරණය කරයි.",
        "## වර්ග අනුව උපරිම සීමා",
        [
          "ප්‍රධාන ශල්‍යකර්ම — වර්ෂයකට සාමාජිකයෙකුට උපරිම <strong>රු. 75,000</strong>",
          "ඩයලිසිස් සහාය — මාස දොළහක් දක්වා මසකට <strong>රු. 8,000</strong>",
          "පිළිකා ප්‍රතිකාර සඳහා ගමන් හා නවාතැන් — උපරිම <strong>රු. 45,000</strong>",
          "දිගුකාලීන ඖෂධ (දියවැඩියා, හෘද, වකුගඩු) — වර්ෂයකට උපරිම <strong>රු. 24,000</strong>",
        ],
        "## ඉල්ලීමක් කිරීම",
        "ඔබේ සාමාජික පුවරුවෙන් සුබසාධක ඉල්ලීමක් විවෘත කරන්න, නැතහොත් විශේෂඥ වෛද්‍ය වාර්තාව සහ රිසිට්පත් සමඟ HLA/W-04 පෝරමය යොමු කරන්න. ඉල්ලීම් සති දෙකකට වරක් පවත්වන සුබසාධක උපකමිටු රැස්වීමේදී සමාලෝචනය කෙරේ. හදිසි අවස්ථා සභාපති සහ භාණ්ඩාගාරික එකට පැය 24ක් ඇතුළත තීරණය කර ඊළඟ රැස්වීමේදී අනුමත කරයි.",
        "## ආවරණය නොවන දේ",
        "රූපලාවණ්‍ය ක්‍රියාපටිපාටි, රක්ෂණකරුවෙකු හෝ සේවා යෝජකයෙකු විසින් දැනටමත් ගෙවා ඇති ප්‍රතිකාර, සහ රජයේ පහසුකමක් තිබූ අවස්ථාවල පෞද්ගලික රෝහල් ගාස්තු. ලේඛනගත හදිසි අවස්ථාවලදී උපකමිටුව විසින් ව්‍යතිරේක ලබා දිය හැක.",
      ]),
      ta: html([
        "இலங்கையின் அரச வைத்தியசாலைகள் இலவச சிகிச்சை வழங்குகின்றன, ஆனால் குடும்பங்கள் ஸ்கேன், இறக்குமதி மருந்துகள், கொழும்பு பயணம் மற்றும் குடும்பத் தலைவர் குணமாகும் காலத்தில் இழக்கும் வருமானம் ஆகியவற்றை எதிர்கொள்கின்றன. இந்த நிதியம் அந்த இடைவெளிகளையே நிரப்புகிறது.",
        "## வகைவாரியான உச்ச வரம்புகள்",
        [
          "பெரிய அறுவைச் சிகிச்சை — ஆண்டுக்கு உறுப்பினர் ஒருவருக்கு <strong>ரூ. 75,000</strong> வரை",
          "சிறுநீரகக் கழுவல் ஆதரவு — பன்னிரண்டு மாதங்கள் வரை மாதம் <strong>ரூ. 8,000</strong>",
          "புற்றுநோய் சிகிச்சைப் பயணம் மற்றும் தங்குமிடம் — <strong>ரூ. 45,000</strong> வரை",
          "நீண்டகால மருந்து (சர்க்கரை, இதயம், சிறுநீரகம்) — ஆண்டுக்கு <strong>ரூ. 24,000</strong> வரை",
        ],
        "## கோரிக்கை சமர்ப்பித்தல்",
        "உங்கள் உறுப்பினர் பலகையிலிருந்து நலன்புரி கோரிக்கையைத் திறங்கள், அல்லது நிபுணர் அறிக்கை மற்றும் ரசீதுகளுடன் HLA/W-04 படிவத்தைச் சமர்ப்பியுங்கள். கோரிக்கைகள் இரு வாரங்களுக்கு ஒருமுறை நடக்கும் நலன்புரி உபகுழுக் கூட்டத்தில் மறுஆய்வு செய்யப்படும். அவசர வழக்குகள் தலைவரும் பொருளாளரும் இணைந்து 24 மணி நேரத்தில் தீர்மானித்து அடுத்த கூட்டத்தில் உறுதிப்படுத்தப்படும்.",
        "## உள்ளடங்காதவை",
        "அழகுசாதன சிகிச்சைகள், காப்புறுதி நிறுவனம் அல்லது முதலாளியால் ஏற்கனவே திரும்பச் செலுத்தப்பட்ட சிகிச்சை, மற்றும் அரச வசதி இருந்த இடத்தில் தனியார் வைத்தியசாலைக் கட்டணங்கள். ஆவணப்படுத்தப்பட்ட அவசர நிலைகளில் உபகுழு விதிவிலக்கு அளிக்கலாம்.",
      ]),
    },
  },
  {
    slug: "scholarship-programme",
    category: "WELFARE",
    icon: "GraduationCap",
    coverImage: "/media/scholarship-award.svg",
    benefitAmount: 60000,
    sortOrder: 3,
    title: tri("Scholarship Programme", "ශිෂ්‍යත්ව වැඩසටහන", "கல்வி உதவித்தொகைத் திட்டம்"),
    summary: tri(
      "Annual scholarships for Grade 5, O/L and A/L students from member families and low-income households.",
      "සාමාජික පවුල් සහ අඩු ආදායම්ලාභී නිවෙස්වල 5 ශ්‍රේණිය, සා.පෙළ සහ උ.පෙළ සිසුන් සඳහා වාර්ෂික ශිෂ්‍යත්ව.",
      "உறுப்பினர் குடும்பங்கள் மற்றும் குறைந்த வருமானக் குடும்பங்களின் 5ஆம் தரம், சா.த மற்றும் உ.த மாணவர்களுக்கு வருடாந்த உதவித்தொகை.",
    ),
    eligibility: tri(
      "Children of members in good standing, and children from households identified by the welfare sub-committee.",
      "යාවත්කාලීන සාමාජිකයින්ගේ දරුවන් සහ සුබසාධක උපකමිටුව විසින් හඳුනාගත් නිවෙස්වල දරුවන්.",
      "நிலுவையின்றி உள்ள உறுப்பினர்களின் பிள்ளைகள், மற்றும் நலன்புரி உபகுழுவால் அடையாளம் காணப்பட்ட குடும்பங்களின் பிள்ளைகள்.",
    ),
    body: {
      en: html([
        "Education is the one intervention that changes a family's trajectory permanently. Since 2016 the association has awarded 312 scholarships, and 44 of our holders have entered state universities.",
        "## Award values for 2026",
        [
          "Grade 5 scholarship holders — <strong>Rs. 24,000</strong> per year",
          "O/L candidates (Grades 10–11) — <strong>Rs. 36,000</strong> per year",
          "A/L candidates (Grades 12–13) — <strong>Rs. 60,000</strong> per year",
        ],
        "Awards are paid in three instalments timed to the school terms, so money arrives when book lists and class fees are actually due.",
        "## Selection",
        "Academic performance carries 50% of the weighting, household income 35% and a short interview with the education sub-committee 15%. Ties are resolved in favour of the lower-income household.",
        "## More than money",
        "Every scholarship holder is paired with a volunteer mentor and invited to three group sessions a year — exam technique, career guidance and a university application clinic for A/L students.",
      ]),
      si: html([
        "පවුලක ගමන් මාර්ගය ස්ථිරව වෙනස් කරන එකම මැදිහත්වීම අධ්‍යාපනයයි. 2016 සිට සමිතිය ශිෂ්‍යත්ව 312 ක් ප්‍රදානය කර ඇති අතර, අපගේ දරුවන් 44 දෙනෙක් රාජ්‍ය විශ්වවිද්‍යාලවලට ඇතුළත් වී ඇත.",
        "## 2026 සඳහා ප්‍රදාන අගයන්",
        [
          "5 ශ්‍රේණිය ශිෂ්‍යත්වලාභීන් — වර්ෂයකට <strong>රු. 24,000</strong>",
          "සා.පෙළ අපේක්ෂකයින් (10–11 ශ්‍රේණි) — වර්ෂයකට <strong>රු. 36,000</strong>",
          "උ.පෙළ අපේක්ෂකයින් (12–13 ශ්‍රේණි) — වර්ෂයකට <strong>රු. 60,000</strong>",
        ],
        "පොත් ලේඛන සහ පන්ති ගාස්තු සැබවින්ම ගෙවිය යුතු විට මුදල් ලැබෙන පරිදි, පාසල් වාරවලට ගැළපෙන ලෙස ප්‍රදාන තුන් වාරයකින් ගෙවනු ලැබේ.",
        "## තේරීම",
        "අධ්‍යාපනික ප්‍රතිඵල 50%, නිවෙස් ආදායම 35% සහ අධ්‍යාපන උපකමිටුව සමඟ කෙටි සම්මුඛ සාකච්ඡාව 15% ලෙස බර තැබේ. සමතුලිත අවස්ථාවලදී අඩු ආදායම්ලාභී නිවෙසට ප්‍රමුඛත්වය දෙනු ලැබේ.",
        "## මුදලට වඩා වැඩි යමක්",
        "සෑම ශිෂ්‍යත්වලාභියෙකුටම ස්වේච්ඡා උපදේශකයෙකු යොදවනු ලබන අතර, වර්ෂයකට කණ්ඩායම් සැසි තුනකට ආරාධනා කෙරේ — විභාග ශිල්පීය ක්‍රම, වෘත්තීය මාර්ගෝපදේශනය සහ උ.පෙළ සිසුන් සඳහා විශ්වවිද්‍යාල අයදුම්පත් සායනයක්.",
      ]),
      ta: html([
        "ஒரு குடும்பத்தின் பாதையை நிரந்தரமாக மாற்றும் ஒரே தலையீடு கல்வியே. 2016 முதல் சங்கம் 312 உதவித்தொகைகளை வழங்கியுள்ளது, எமது 44 மாணவர்கள் அரச பல்கலைக்கழகங்களில் இணைந்துள்ளனர்.",
        "## 2026 ஆம் ஆண்டு உதவித்தொகை மதிப்புகள்",
        [
          "5ஆம் தரப் புலமைப்பரிசில் பெற்றோர் — ஆண்டுக்கு <strong>ரூ. 24,000</strong>",
          "சா.த மாணவர்கள் (10–11 தரம்) — ஆண்டுக்கு <strong>ரூ. 36,000</strong>",
          "உ.த மாணவர்கள் (12–13 தரம்) — ஆண்டுக்கு <strong>ரூ. 60,000</strong>",
        ],
        "பாட நூல் பட்டியல்களும் வகுப்புக் கட்டணங்களும் உண்மையில் செலுத்த வேண்டிய நேரத்தில் பணம் கிடைக்கும் வகையில், பாடசாலைப் பருவங்களுக்கு ஏற்ப மூன்று தவணைகளில் வழங்கப்படுகிறது.",
        "## தேர்வு",
        "கல்வித் தரம் 50%, குடும்ப வருமானம் 35%, கல்வி உபகுழுவுடனான குறுகிய நேர்காணல் 15% என எடையிடப்படுகிறது. சமநிலையில் குறைந்த வருமானக் குடும்பத்திற்கு முன்னுரிமை.",
        "## பணத்தை விட மேலானது",
        "ஒவ்வொரு உதவித்தொகை பெறுநருக்கும் ஒரு தொண்டர் வழிகாட்டி இணைக்கப்படுகிறார், ஆண்டுக்கு மூன்று குழு அமர்வுகளுக்கு அழைக்கப்படுகிறார் — பரீட்சை உத்திகள், தொழில் வழிகாட்டல், உ.த மாணவர்களுக்கு பல்கலைக்கழக விண்ணப்ப ஆலோசனை.",
      ]),
    },
  },
  {
    slug: "disaster-relief",
    category: "EMERGENCY",
    icon: "CloudRainWind",
    coverImage: "/media/flood-relief.svg",
    benefitAmount: 50000,
    sortOrder: 4,
    title: tri("Disaster Relief", "ආපදා සහන", "பேரிடர் நிவாரணம்"),
    summary: tri(
      "Rapid response for families hit by flood, landslide, storm or fire — dry rations within 24 hours and a rebuilding grant after assessment.",
      "ගංවතුර, නායයෑම්, කුණාටු හෝ ගිනි ගැනීම්වලින් පීඩාවට පත් පවුල් සඳහා ක්ෂණික ප්‍රතිචාරය — පැය 24ක් ඇතුළත වියළි ආහාර සහ ඇස්තමේන්තුවෙන් පසු නැවත ගොඩනැගීමේ ආධාරය.",
      "வெள்ளம், மண்சரிவு, புயல் அல்லது தீ விபத்தால் பாதிக்கப்பட்ட குடும்பங்களுக்கு விரைவு நடவடிக்கை — 24 மணி நேரத்தில் உலர் உணவும், மதிப்பீட்டுக்குப் பின் மீள்கட்டுமான உதவியும்.",
    ),
    eligibility: tri(
      "Open to members and to non-member households in affected areas, on the recommendation of the local grama niladhari.",
      "පීඩිත ප්‍රදේශවල සාමාජිකයින්ට සහ ග්‍රාම නිලධාරීගේ නිර්දේශය මත සාමාජික නොවන නිවෙස්වලටද විවෘතය.",
      "பாதிக்கப்பட்ட பகுதிகளில் உறுப்பினர்களுக்கும், கிராம சேவகரின் பரிந்துரையின் பேரில் உறுப்பினர் அல்லாத குடும்பங்களுக்கும் திறந்திருக்கிறது.",
    ),
    body: {
      en: html([
        "Disaster relief is the one scheme where we do not ask whether you are a member. When water enters a house, the association responds to the street, not the membership register.",
        "## Stage one — within 24 hours",
        "Volunteer teams deliver dry ration packs (rice, dhal, coconut, sugar, tea, soap and a water container), sleeping mats and a torch. Packs are sized for a family of four for fourteen days.",
        "## Stage two — assessment",
        "Within a week a two-person team records damage with photographs and a standard form. Households are graded fully damaged, partially damaged or contents-only.",
        "## Stage three — rebuilding grant",
        [
          "Fully damaged house — up to <strong>Rs. 50,000</strong> plus materials sourced at cost",
          "Partially damaged — up to <strong>Rs. 25,000</strong>",
          "Contents and household goods — up to <strong>Rs. 12,000</strong>",
        ],
        "## Coordination",
        "We work through the Divisional Secretariat to avoid duplicating state relief, and publish every disbursement in the spending ledger on our transparency page.",
      ]),
      si: html([
        "ඔබ සාමාජිකයෙක්ද යන්න අපි නොඅසන එකම යෝජනා ක්‍රමය ආපදා සහනයයි. නිවසකට ජලය ඇතුළු වූ විට, සමිතිය ප්‍රතිචාර දක්වන්නේ සාමාජික ලේඛනයට නොව, එම වීදියටයි.",
        "## පළමු අදියර — පැය 24ක් ඇතුළත",
        "ස්වේච්ඡා කණ්ඩායම් වියළි ආහාර මලු (සහල්, පරිප්පු, පොල්, සීනි, තේ, සබන් සහ ජල භාජනයක්), නිදාගැනීමේ පැදුරු සහ ටෝච් ලාම්පුවක් බෙදා දෙයි. මලු සිව් දෙනෙකුගේ පවුලකට දින දාහතරක් සඳහා සකසා ඇත.",
        "## දෙවන අදියර — ඇස්තමේන්තු කිරීම",
        "සතියක් ඇතුළත දෙදෙනෙකුගෙන් යුත් කණ්ඩායමක් ඡායාරූප සහ සම්මත පෝරමයක් සමඟ හානිය සටහන් කරයි. නිවෙස් සම්පූර්ණයෙන් හානි වූ, අර්ධ වශයෙන් හානි වූ හෝ බඩු පමණක් හානි වූ ලෙස වර්ග කෙරේ.",
        "## තෙවන අදියර — නැවත ගොඩනැගීමේ ආධාරය",
        [
          "සම්පූර්ණයෙන් හානි වූ නිවස — උපරිම <strong>රු. 50,000</strong> සහ පිරිවැය මිලට ලබා දෙන ද්‍රව්‍ය",
          "අර්ධ වශයෙන් හානි වූ — උපරිම <strong>රු. 25,000</strong>",
          "බඩු මුට්ටු සහ ගෘහ භාණ්ඩ — උපරිම <strong>රු. 12,000</strong>",
        ],
        "## සම්බන්ධීකරණය",
        "රාජ්‍ය සහන සමඟ අනුපිටපත් වීම වළක්වා ගැනීමට අපි ප්‍රාදේශීය ලේකම් කාර්යාලය හරහා කටයුතු කරන අතර, සෑම ගෙවීමක්ම අපගේ විනිවිදභාව පිටුවේ වියදම් ලෙජරයේ ප්‍රකාශයට පත් කරමු.",
      ]),
      ta: html([
        "நீங்கள் உறுப்பினரா என்று நாம் கேட்காத ஒரே திட்டம் பேரிடர் நிவாரணமே. ஒரு வீட்டுக்குள் நீர் புகும்போது, சங்கம் உறுப்பினர் பட்டியலுக்கு அல்ல, அந்த வீதிக்கே பதிலளிக்கிறது.",
        "## முதல் கட்டம் — 24 மணி நேரத்தில்",
        "தொண்டர் குழுக்கள் உலர் உணவுப் பொதிகள் (அரிசி, பருப்பு, தேங்காய், சீனி, தேயிலை, சவர்க்காரம், நீர்க் கொள்கலன்), படுக்கைப் பாய்கள் மற்றும் ஒரு டோர்ச் விளக்கை வழங்குகின்றன. பொதிகள் நான்கு பேர் கொண்ட குடும்பத்திற்கு பதினான்கு நாட்களுக்கு ஏற்ப தயாரிக்கப்பட்டவை.",
        "## இரண்டாம் கட்டம் — மதிப்பீடு",
        "ஒரு வாரத்தில் இருவர் கொண்ட குழு புகைப்படங்கள் மற்றும் நியம படிவத்துடன் சேதத்தைப் பதிவு செய்யும். வீடுகள் முழுமையாகச் சேதமானது, பகுதியாகச் சேதமானது, அல்லது பொருட்கள் மட்டும் எனத் தரப்படுத்தப்படும்.",
        "## மூன்றாம் கட்டம் — மீள்கட்டுமான உதவி",
        [
          "முழுமையாகச் சேதமான வீடு — <strong>ரூ. 50,000</strong> வரை மற்றும் அடக்க விலையில் பொருட்கள்",
          "பகுதியாகச் சேதமானது — <strong>ரூ. 25,000</strong> வரை",
          "வீட்டுப் பொருட்கள் — <strong>ரூ. 12,000</strong> வரை",
        ],
        "## ஒருங்கிணைப்பு",
        "அரச நிவாரணத்துடன் இரட்டிப்பாகாமல் இருக்க பிரதேச செயலகம் வழியாகச் செயற்படுகிறோம், ஒவ்வொரு வழங்கலையும் எமது வெளிப்படைத்தன்மைப் பக்கத்தின் செலவுப் பேரேட்டில் வெளியிடுகிறோம்.",
      ]),
    },
  },
  {
    slug: "emergency-hospital-transport",
    category: "EMERGENCY",
    icon: "Ambulance",
    coverImage: "/media/health-awareness.svg",
    benefitAmount: 15000,
    sortOrder: 5,
    title: tri("Emergency Hospital Transport", "හදිසි රෝහල් ප්‍රවාහනය", "அவசர வைத்தியசாலைப் போக்குவரத்து"),
    summary: tri(
      "A 24-hour hotline that arranges and pays for transport to hospital, including transfers to specialist units in Colombo.",
      "කොළඹ විශේෂඥ ඒකකවලට මාරු කිරීම් ඇතුළුව රෝහලට ප්‍රවාහනය සකසා ගෙවන පැය 24 හදිසි ඇමතුම් සේවාව.",
      "கொழும்பு நிபுணத்துவ பிரிவுகளுக்கு மாற்றுவது உட்பட வைத்தியசாலைக்குப் போக்குவரத்தை ஏற்பாடு செய்து கட்டணம் செலுத்தும் 24 மணி நேர அவசர சேவை.",
    ),
    eligibility: tri(
      "All members and their household. Non-members are assisted and invoiced at cost where possible.",
      "සියලු සාමාජිකයින් සහ ඔවුන්ගේ නිවෙස. සාමාජික නොවන අයට හැකි විට පිරිවැය මිලට සහාය දෙනු ලැබේ.",
      "அனைத்து உறுப்பினர்களும் அவர்களது குடும்பமும். உறுப்பினர் அல்லாதவர்களுக்கு இயன்ற இடத்து அடக்க விலையில் உதவி வழங்கப்படும்.",
    ),
    body: {
      en: html([
        "Getting to hospital is the first barrier in a rural emergency. The association maintains a rota of eleven volunteer drivers and a standing arrangement with two ambulance operators.",
        "## What the hotline does",
        [
          "Dispatches the nearest volunteer driver or a contracted ambulance",
          "Pays the fare directly, so the family never has to find cash at 2 a.m.",
          "Calls ahead to the hospital where a transfer letter is needed",
          "Arranges an attendant to stay with the patient when the family cannot",
        ],
        "## Cover",
        "Up to <strong>Rs. 15,000</strong> per incident, with no annual limit on the number of incidents. Long-distance transfers to Colombo specialist units are approved by the duty officer without a committee meeting.",
        "## Volunteer drivers",
        "If you own a vehicle and can be on call one night a fortnight, this is the single most useful thing you can volunteer for. Register through the volunteer form and select “Logistics & distribution”.",
      ]),
      si: html([
        "ග්‍රාමීය හදිසි අවස්ථාවක පළමු බාධකය රෝහලට ළඟා වීමයි. සමිතිය ස්වේච්ඡා රියදුරන් එකොළොස් දෙනෙකුගේ වාරාවලියක් සහ ගිලන් රථ ක්‍රියාකරුවන් දෙදෙනෙකු සමඟ ස්ථාවර සැලසුමක් පවත්වා ගෙන යයි.",
        "## හදිසි ඇමතුම් සේවාව කරන දේ",
        [
          "ළඟම ස්වේච්ඡා රියදුරු හෝ කොන්ත්‍රාත් ගිලන් රථය යොමු කිරීම",
          "ගාස්තුව සෘජුවම ගෙවීම, එබැවින් පවුලට රාත්‍රී 2ට මුදල් සොයා ගැනීමට අවශ්‍ය නොවේ",
          "මාරු කිරීමේ ලිපියක් අවශ්‍ය රෝහලට කලින් දැනුම් දීම",
          "පවුලට නොහැකි විට රෝගියා සමඟ රැඳී සිටීමට උපස්ථායකයෙකු සැපයීම",
        ],
        "## ආවරණය",
        "එක් සිදුවීමකට උපරිම <strong>රු. 15,000</strong>, සිදුවීම් ගණනට වාර්ෂික සීමාවක් නොමැත. කොළඹ විශේෂඥ ඒකකවලට දිගු දුර මාරු කිරීම් කමිටු රැස්වීමකින් තොරව රාජකාරි නිලධාරියා විසින් අනුමත කරයි.",
        "## ස්වේච්ඡා රියදුරන්",
        "ඔබට වාහනයක් ඇත්නම් සහ සති දෙකකට එක් රාත්‍රියක් සූදානම්ව සිටිය හැකි නම්, ඔබට ස්වේච්ඡාවෙන් කළ හැකි වඩාත් ප්‍රයෝජනවත් දෙය මෙයයි. ස්වේච්ඡා පෝරමය හරහා ලියාපදිංචි වී “සැපයුම් හා බෙදාහැරීම” තෝරන්න.",
      ]),
      ta: html([
        "கிராமிய அவசர நிலையில் முதல் தடை வைத்தியசாலையை அடைவதே. சங்கம் பதினொரு தொண்டர் சாரதிகளின் சுழற்சி முறையையும், இரு அம்பியுலன்ஸ் இயக்குநர்களுடன் நிலையான ஏற்பாட்டையும் பராமரிக்கிறது.",
        "## அவசர இலக்கம் செய்வது",
        [
          "அருகிலுள்ள தொண்டர் சாரதி அல்லது ஒப்பந்த அம்பியுலன்ஸை அனுப்புதல்",
          "கட்டணத்தை நேரடியாகச் செலுத்துதல், எனவே குடும்பம் இரவு 2 மணிக்குப் பணம் தேட வேண்டியதில்லை",
          "மாற்றுக் கடிதம் தேவைப்படும் வைத்தியசாலைக்கு முன்னதாக அறிவித்தல்",
          "குடும்பத்தால் இயலாதபோது நோயாளியுடன் தங்க ஒருவரை ஏற்பாடு செய்தல்",
        ],
        "## பாதுகாப்பு வரம்பு",
        "ஒரு சம்பவத்திற்கு <strong>ரூ. 15,000</strong> வரை, சம்பவங்களின் எண்ணிக்கைக்கு வருடாந்த வரம்பு இல்லை. கொழும்பு நிபுணத்துவ பிரிவுகளுக்கான நெடுந்தூர மாற்றங்கள் குழுக் கூட்டமின்றி கடமை அதிகாரியால் அனுமதிக்கப்படும்.",
        "## தொண்டர் சாரதிகள்",
        "உங்களுக்கு வாகனம் இருந்து, இரு வாரங்களுக்கு ஒரு இரவு தயாராக இருக்க முடிந்தால், நீங்கள் தொண்டாற்றக்கூடிய மிகப் பயனுள்ள செயல் இதுவே. தொண்டர் படிவம் வழியாகப் பதிவு செய்து “விநியோகம் & பொருள் கையாளல்” தேர்ந்தெடுங்கள்.",
      ]),
    },
  },
  {
    slug: "hardship-grant",
    category: "EMERGENCY",
    icon: "LifeBuoy",
    coverImage: "/media/food-distribution.svg",
    benefitAmount: 30000,
    sortOrder: 6,
    title: tri("Sudden Hardship Grant", "හදිසි අපහසුතා ආධාරය", "திடீர் நெருக்கடி உதவி"),
    summary: tri(
      "A discretionary grant for families facing sudden loss of income through injury, retrenchment or the illness of a breadwinner.",
      "තුවාල, රැකියා අහිමි වීම හෝ ආදායම් ලබන්නාගේ රෝගී තත්ත්වය නිසා හදිසියේ ආදායම අහිමි වූ පවුල් සඳහා අභිමතානුසාරී ආධාරයක්.",
      "காயம், வேலை இழப்பு அல்லது குடும்பத் தலைவரின் நோய் காரணமாக திடீரென வருமானம் இழந்த குடும்பங்களுக்கான தற்றுணிபு உதவி.",
    ),
    eligibility: tri(
      "Assessed case by case by the welfare sub-committee after a home visit.",
      "නිවෙස් සංචාරයකින් පසු සුබසාධක උපකමිටුව විසින් එක් එක් අවස්ථාව අනුව ඇස්තමේන්තු කෙරේ.",
      "வீட்டு வருகைக்குப் பின் நலன்புரி உபகுழுவால் தனித்தனியாக மதிப்பிடப்படும்.",
    ),
    body: {
      en: html([
        "Some situations do not fit any scheme. A mason falls from scaffolding and cannot work for four months. A factory closes with two weeks' notice. A mother becomes the sole carer for a parent with dementia.",
        "The hardship grant exists for exactly these cases. It is deliberately discretionary, decided by people who have visited the home.",
        "## What is available",
        [
          "A monthly payment of up to <strong>Rs. 10,000</strong> for up to three months",
          "A one-off payment of up to <strong>Rs. 30,000</strong> to clear an urgent debt or fee",
          "School fees and book costs paid directly to the school",
          "A dry ration pack every fortnight for the duration of the grant",
        ],
        "## How to ask",
        "Speak to any committee member, call the office, or open a support ticket from the member dashboard under “Welfare claim”. There is no form to start the process — a conversation is enough.",
      ]),
      si: html([
        "සමහර තත්ත්වයන් කිසිදු යෝජනා ක්‍රමයකට නොගැළපේ. මේසන් බාස්උන්නෑහේ ඉස්කෙලෙන් වැටී මාස හතරක් වැඩ කළ නොහැක. කර්මාන්තශාලාවක් සති දෙකක දැනුම්දීමකින් වැසේ. මවක් ඩිමෙන්ෂියාවෙන් පෙළෙන දෙමාපියෙකුගේ එකම රැකවරණකරු වේ.",
        "අපහසුතා ආධාරය පවතින්නේ හරියටම මෙවැනි අවස්ථා සඳහාය. එය හිතාමතාම අභිමතානුසාරී වන අතර, නිවෙසට ගොස් බලා ඇති පුද්ගලයින් විසින් තීරණය කරනු ලැබේ.",
        "## ලබා ගත හැකි දේ",
        [
          "මාස තුනක් දක්වා මාසිකව උපරිම <strong>රු. 10,000</strong> ගෙවීමක්",
          "හදිසි ණයක් හෝ ගාස්තුවක් පියවීමට එක් වාරයක උපරිම <strong>රු. 30,000</strong> ගෙවීමක්",
          "පාසල් ගාස්තු සහ පොත් වියදම් සෘජුවම පාසලට ගෙවීම",
          "ආධාරය පවතින කාලය තුළ සති දෙකකට වරක් වියළි ආහාර මල්ලක්",
        ],
        "## ඉල්ලන ආකාරය",
        "කවර හෝ කමිටු සාමාජිකයෙකු සමඟ කතා කරන්න, කාර්යාලයට කතා කරන්න, නැතහොත් සාමාජික පුවරුවේ “සුබසාධක ඉල්ලීම” යටතේ සහාය ටිකට්පතක් විවෘත කරන්න. ක්‍රියාවලිය ආරම්භ කිරීමට පෝරමයක් නොමැත — සංවාදයක් ප්‍රමාණවත්.",
      ]),
      ta: html([
        "சில நிலைமைகள் எந்தத் திட்டத்திற்கும் பொருந்தாது. கொத்தனார் ஒருவர் சாரத்திலிருந்து விழுந்து நான்கு மாதம் வேலை செய்ய முடியாமல் போகிறார். தொழிற்சாலை இரு வார அறிவிப்பில் மூடப்படுகிறது. ஒரு தாய் மறதி நோயுள்ள பெற்றோரின் ஒரே பராமரிப்பாளராகிறார்.",
        "நெருக்கடி உதவி இத்தகைய வழக்குகளுக்கே உள்ளது. இது வேண்டுமென்றே தற்றுணிபுக்கு விடப்பட்டது, வீட்டுக்குச் சென்று பார்த்தவர்களால் தீர்மானிக்கப்படுகிறது.",
        "## கிடைக்கும் உதவி",
        [
          "மூன்று மாதங்கள் வரை மாதம் <strong>ரூ. 10,000</strong> வரையான கட்டணம்",
          "அவசரக் கடன் அல்லது கட்டணத்தைத் தீர்க்க ஒருமுறை <strong>ரூ. 30,000</strong> வரை",
          "பாடசாலைக் கட்டணமும் நூல் செலவும் நேரடியாகப் பாடசாலைக்கு",
          "உதவி வழங்கப்படும் காலம் முழுவதும் இரு வாரங்களுக்கு ஒரு உலர் உணவுப் பொதி",
        ],
        "## கேட்கும் முறை",
        "எந்தக் குழு உறுப்பினருடனும் பேசுங்கள், அலுவலகத்தை அழையுங்கள், அல்லது உறுப்பினர் பலகையில் “நலன்புரி கோரிக்கை” என்பதன் கீழ் ஆதரவு டிக்கெட்டைத் திறங்கள். செயல்முறையைத் தொடங்க படிவம் தேவையில்லை — ஒரு உரையாடல் போதும்.",
      ]),
    },
  },
  {
    slug: "member-savings-and-loans",
    category: "MEMBER_SUPPORT",
    icon: "PiggyBank",
    coverImage: "/media/committee-meeting.svg",
    benefitAmount: 100000,
    sortOrder: 7,
    title: tri("Savings & Interest-Free Loans", "ඉතුරුම් හා පොලී රහිත ණය", "சேமிப்பு & வட்டியில்லாக் கடன்"),
    summary: tri(
      "A member savings pool that provides interest-free loans for school fees, self-employment tools and medical bills.",
      "පාසල් ගාස්තු, ස්වයං රැකියා උපකරණ සහ වෛද්‍ය බිල්පත් සඳහා පොලී රහිත ණය සපයන සාමාජික ඉතුරුම් අරමුදලක්.",
      "பாடசாலைக் கட்டணம், சுயதொழில் கருவிகள், மருத்துவ பில்களுக்கு வட்டியில்லாக் கடன் வழங்கும் உறுப்பினர் சேமிப்பு நிதியம்.",
    ),
    eligibility: tri(
      "Members who have contributed to the savings pool for at least twelve months.",
      "අවම මාස දොළහක් ඉතුරුම් අරමුදලට දායක වී ඇති සාමාජිකයින්.",
      "குறைந்தது பன்னிரண்டு மாதங்கள் சேமிப்பு நிதியத்திற்குப் பங்களித்த உறுப்பினர்கள்.",
    ),
    body: {
      en: html([
        "Informal lenders in our areas charge between 10% and 20% a month. A single Rs. 40,000 loan for a school admission can turn into a permanent debt. This scheme was created to break that cycle.",
        "## How it works",
        "Members contribute a minimum of Rs. 500 a month to the savings pool. After twelve months a member may borrow up to three times their accumulated savings, capped at <strong>Rs. 100,000</strong>, repayable over twenty-four months with <strong>no interest</strong> and no processing fee.",
        "## Permitted purposes",
        [
          "School and university admission fees, books and equipment",
          "Tools, a sewing machine, a display cabinet or stock for self-employment",
          "Medical bills not covered by the medical assistance fund",
          "Essential house repairs",
        ],
        "## Guarantors and recovery",
        "Two members in good standing act as guarantors. Recovery is by standing order or at the monthly branch meeting. Where a borrower falls into genuine difficulty the committee reschedules rather than pursues — in nine years the scheme has written off less than 2% of the value lent.",
      ]),
      si: html([
        "අපගේ ප්‍රදේශවල අවිධිමත් ණය දෙන්නන් මසකට 10% ත් 20% ත් අතර පොලියක් ගනී. පාසල් ඇතුළත් කිරීමක් සඳහා ගන්නා රු. 40,000ක ණයක් ස්ථිර ණයක් බවට පත් විය හැක. එම චක්‍රය බිඳ දැමීමට මෙම යෝජනා ක්‍රමය නිර්මාණය කරන ලදී.",
        "## ක්‍රියාත්මක වන ආකාරය",
        "සාමාජිකයින් මසකට අවම රු. 500 ක් ඉතුරුම් අරමුදලට දායක වේ. මාස දොළහකට පසු සාමාජිකයෙකුට තම රැස් වූ ඉතුරුම්වලින් තුන් ගුණයක් දක්වා, උපරිම <strong>රු. 100,000</strong> දක්වා, මාස විසිහතරකින් <strong>පොලී රහිතව</strong> සහ සැකසුම් ගාස්තුවකින් තොරව ආපසු ගෙවිය හැකි ණයක් ලබා ගත හැක.",
        "## අනුමත අරමුණු",
        [
          "පාසල් හා විශ්වවිද්‍යාල ඇතුළත් වීමේ ගාස්තු, පොත් සහ උපකරණ",
          "ස්වයං රැකියාව සඳහා උපකරණ, මැෂිමක්, ප්‍රදර්ශන කබඩයක් හෝ තොග",
          "වෛද්‍ය ආධාර අරමුදලින් ආවරණය නොවන වෛද්‍ය බිල්පත්",
          "අත්‍යවශ්‍ය නිවාස අලුත්වැඩියා",
        ],
        "## ඇපකරුවන් සහ අයකර ගැනීම",
        "යාවත්කාලීන සාමාජිකයින් දෙදෙනෙක් ඇපකරුවන් ලෙස කටයුතු කරයි. අයකර ගැනීම ස්ථාවර නියෝගයකින් හෝ මාසික ශාඛා රැස්වීමේදී සිදු වේ. ණය ගැනුම්කරු සැබෑ අපහසුතාවකට පත් වූ විට කමිටුව එළවා නොයමින් කාලසටහන යළි සකසයි — වර්ෂ නවයක් තුළ මෙම යෝජනා ක්‍රමය ණයට දුන් වටිනාකමින් 2% ට අඩුවක් අක්‍රීය කර ඇත.",
      ]),
      ta: html([
        "எமது பகுதிகளில் முறைசாரா கடன் வழங்குபவர்கள் மாதம் 10% முதல் 20% வரை வட்டி வசூலிக்கின்றனர். பாடசாலை அனுமதிக்கான ரூ. 40,000 கடன் நிரந்தரக் கடனாக மாறலாம். அந்தச் சுழற்சியை உடைக்கவே இந்தத் திட்டம் உருவாக்கப்பட்டது.",
        "## செயற்படும் விதம்",
        "உறுப்பினர்கள் மாதம் குறைந்தது ரூ. 500 சேமிப்பு நிதியத்திற்குப் பங்களிக்கிறார்கள். பன்னிரண்டு மாதங்களுக்குப் பின் உறுப்பினர் தமது சேமிப்பின் மூன்று மடங்கு வரை, அதிகபட்சம் <strong>ரூ. 100,000</strong> வரை, இருபத்திநான்கு மாதங்களில் <strong>வட்டியில்லாமல்</strong>, செயலாக்கக் கட்டணமின்றித் திரும்பச் செலுத்தும் கடன் பெறலாம்.",
        "## அனுமதிக்கப்பட்ட நோக்கங்கள்",
        [
          "பாடசாலை, பல்கலைக்கழக அனுமதிக் கட்டணம், நூல்கள், உபகரணங்கள்",
          "சுயதொழிலுக்கான கருவிகள், தையல் இயந்திரம், காட்சிப் பேழை அல்லது சரக்கு",
          "மருத்துவ உதவி நிதியத்தில் உள்ளடங்காத மருத்துவ பில்கள்",
          "அத்தியாவசிய வீட்டுப் பழுதுபார்ப்பு",
        ],
        "## உத்தரவாதர்களும் மீட்பும்",
        "நிலுவையின்றி உள்ள இரு உறுப்பினர்கள் உத்தரவாதராகச் செயற்படுவர். மீட்பு நிலையான உத்தரவு மூலமாக அல்லது மாதாந்தக் கிளைக் கூட்டத்தில் நடைபெறும். கடன் பெற்றவர் உண்மையான சிரமத்தில் இருக்கும்போது குழு துரத்தாமல் காலஅட்டவணையை மாற்றுகிறது — ஒன்பது ஆண்டுகளில் வழங்கிய தொகையில் 2% க்கும் குறைவாகவே தள்ளுபடி செய்யப்பட்டுள்ளது.",
      ]),
    },
  },
  {
    slug: "elders-support",
    category: "MEMBER_SUPPORT",
    icon: "Users",
    coverImage: "/media/elders-day.svg",
    benefitAmount: 6000,
    sortOrder: 8,
    title: tri("Elders' Support", "වැඩිහිටි සහාය", "முதியோர் ஆதரவு"),
    summary: tri(
      "A monthly allowance, home visits and a day centre for members over seventy who live alone or have no income.",
      "තනිව ජීවත් වන හෝ ආදායමක් නොමැති සත්තෑ වයස ඉක්මවූ සාමාජිකයින් සඳහා මාසික දීමනාවක්, නිවෙස් සංචාර සහ දිවා මධ්‍යස්ථානයක්.",
      "தனியாக வாழும் அல்லது வருமானமில்லாத எழுபது வயதுக்கு மேற்பட்ட உறுப்பினர்களுக்கு மாதாந்த கொடுப்பனவு, வீட்டு வருகைகள் மற்றும் பகல் நிலையம்.",
    ),
    eligibility: tri(
      "Members over seventy with no pension or regular income, or living without family support.",
      "විශ්‍රාම වැටුපක් හෝ නිත්‍ය ආදායමක් නොමැති, නැතහොත් පවුලේ සහායකින් තොරව ජීවත් වන සත්තෑ ඉක්මවූ සාමාජිකයින්.",
      "ஓய்வூதியம் அல்லது நிலையான வருமானமில்லாத, அல்லது குடும்ப ஆதரவின்றி வாழும் எழுபது வயதுக்கு மேற்பட்ட உறுப்பினர்கள்.",
    ),
    body: {
      en: html([
        "Fifty-eight of our members are over seventy. Nineteen of them live alone. This programme is our commitment that long service to the association is repaid.",
        "## What members receive",
        [
          "A monthly allowance of <strong>Rs. 6,000</strong> paid on the first of the month",
          "A fortnightly home visit from a trained volunteer",
          "Free entry to the Wednesday day centre, including lunch and a health check",
          "Priority access to the medical assistance fund with no waiting period",
          "Spectacles, hearing aids and mobility aids provided at no cost",
        ],
        "## The Wednesday day centre",
        "Held at the community hall in Nugegoda. Sessions include physiotherapy, a nurse-led blood pressure and sugar clinic, carrom and draughts, and a hot lunch. Transport is arranged for anyone within twelve kilometres.",
        "## Subscriptions waived",
        "Members over seventy-five pay no monthly subscription but retain full voting rights and full welfare cover.",
      ]),
      si: html([
        "අපගේ සාමාජිකයින් 58 දෙනෙක් සත්තෑ වයස ඉක්මවා ඇත. ඔවුන්ගෙන් 19 දෙනෙක් තනිව ජීවත් වේ. සමිතියට කළ දිගු සේවය ආපසු ගෙවනු ලබන බවට අපගේ කැපවීම මෙම වැඩසටහනයි.",
        "## සාමාජිකයින්ට ලැබෙන දේ",
        [
          "මාසයේ පළමු දිනට ගෙවන මාසික දීමනාවක් <strong>රු. 6,000</strong>",
          "පුහුණු ස්වේච්ඡා සේවකයෙකුගෙන් සති දෙකකට වරක් නිවෙස් සංචාරයක්",
          "දිවා ආහාරය සහ සෞඛ්‍ය පරීක්ෂණය ඇතුළුව බදාදා දිවා මධ්‍යස්ථානයට නොමිලේ ඇතුළත් වීම",
          "පොරොත්තු කාලයකින් තොරව වෛද්‍ය ආධාර අරමුදලට ප්‍රමුඛ ප්‍රවේශය",
          "නොමිලේ සපයන කණ්නාඩි, ශ්‍රවණ උපකරණ සහ ගමන් උපකරණ",
        ],
        "## බදාදා දිවා මධ්‍යස්ථානය",
        "නුගේගොඩ ප්‍රජා ශාලාවේ පවත්වනු ලැබේ. සැසිවලට භෞත චිකිත්සාව, හෙදියක් මගින් පවත්වන රුධිර පීඩන හා සීනි සායනය, කැරම් සහ දාම් ක්‍රීඩා, සහ උණුසුම් දිවා ආහාරය ඇතුළත් වේ. කිලෝමීටර් දොළහක් ඇතුළත සිටින කවුරුන් සඳහාත් ප්‍රවාහනය සකසනු ලැබේ.",
        "## දායක මුදල් අත්හිටුවීම",
        "වයස 75 ඉක්මවූ සාමාජිකයින් මාසික දායක මුදලක් නොගෙවන නමුත් සම්පූර්ණ ඡන්ද අයිතිය සහ සම්පූර්ණ සුබසාධක ආවරණය රඳවා ගනී.",
      ]),
      ta: html([
        "எமது உறுப்பினர்களில் ஐம்பத்தெட்டு பேர் எழுபது வயதுக்கு மேற்பட்டவர்கள். அவர்களில் பத்தொன்பது பேர் தனியாக வாழ்கிறார்கள். சங்கத்திற்குச் செய்த நீண்ட சேவை திருப்பிச் செலுத்தப்படும் என்பதற்கான எமது உறுதிமொழி இந்தத் திட்டம்.",
        "## உறுப்பினர்கள் பெறுவது",
        [
          "மாதத்தின் முதல் நாளில் வழங்கப்படும் மாதாந்த கொடுப்பனவு <strong>ரூ. 6,000</strong>",
          "பயிற்றப்பட்ட தொண்டரின் இரு வாரங்களுக்கு ஒரு வீட்டு வருகை",
          "மதிய உணவும் சுகாதாரப் பரிசோதனையும் உள்ளிட்ட புதன்கிழமை பகல் நிலையத்திற்கு இலவச நுழைவு",
          "காத்திருப்புக் காலமின்றி மருத்துவ உதவி நிதியத்திற்கு முன்னுரிமை",
          "மூக்குக் கண்ணாடி, செவித்துணை கருவி, நடமாட்டக் கருவிகள் இலவசம்",
        ],
        "## புதன்கிழமை பகல் நிலையம்",
        "நுகேகொடை சமூக மண்டபத்தில் நடைபெறுகிறது. அமர்வுகளில் இயன்முறை சிகிச்சை, தாதியர் நடத்தும் இரத்த அழுத்தம் மற்றும் சர்க்கரை கிளினிக், கரம் மற்றும் தாயம் விளையாட்டு, சூடான மதிய உணவு அடங்கும். பன்னிரண்டு கிலோமீட்டர் எல்லைக்குள் உள்ள அனைவருக்கும் போக்குவரத்து ஏற்பாடு.",
        "## சந்தா தள்ளுபடி",
        "எழுபத்தைந்து வயதுக்கு மேற்பட்ட உறுப்பினர்கள் மாதாந்த சந்தா செலுத்த வேண்டியதில்லை, ஆனால் முழு வாக்குரிமையும் முழு நலன்புரி பாதுகாப்பும் தொடரும்.",
      ]),
    },
  },
  {
    slug: "skills-and-livelihood-training",
    category: "MEMBER_SUPPORT",
    icon: "Wrench",
    coverImage: "/media/volunteer-training.svg",
    sortOrder: 9,
    title: tri("Skills & Livelihood Training", "නිපුණතා හා ජීවනෝපාය පුහුණුව", "திறன் & வாழ்வாதார பயிற்சி"),
    summary: tri(
      "Free short courses in tailoring, food processing, mobile repair and digital literacy, with a starter grant on completion.",
      "මැහුම්, ආහාර සැකසීම, ජංගම දුරකථන අලුත්වැඩියා සහ ඩිජිටල් සාක්ෂරතාව පිළිබඳ නොමිලේ කෙටිකාලීන පාඨමාලා, සම්පූර්ණ කිරීමේදී ආරම්භක ආධාරයක් සමඟ.",
      "தையல், உணவுப் பதப்படுத்தல், கைபேசி பழுதுபார்ப்பு, digital எழுத்தறிவு ஆகியவற்றில் இலவச குறுங்கால பாடநெறிகள், நிறைவில் தொடக்க உதவியுடன்.",
    ),
    eligibility: tri(
      "Members, their spouses and children over sixteen. Priority to households with no regular income.",
      "සාමාජිකයින්, ඔවුන්ගේ කලත්‍රයන් සහ වයස 16 ඉක්මවූ දරුවන්. නිත්‍ය ආදායමක් නොමැති නිවෙස්වලට ප්‍රමුඛත්වය.",
      "உறுப்பினர்கள், அவர்களது வாழ்க்கைத் துணைவர், பதினாறு வயதுக்கு மேற்பட்ட பிள்ளைகள். நிலையான வருமானமில்லாத குடும்பங்களுக்கு முன்னுரிமை.",
    ),
    body: {
      en: html([
        "Handouts help for a month; a skill helps for a decade. Every course we run ends with a practical assessment and a starter grant, because training without capital rarely turns into income.",
        "## Courses offered in 2026",
        [
          "Industrial tailoring — 8 weeks, 3 evenings a week",
          "Food processing and packaging (jam, chilli paste, dried fish) — 6 weeks",
          "Mobile phone and small appliance repair — 10 weeks",
          "Digital literacy and online selling — 6 weeks",
          "Three-wheeler maintenance and safe driving — 4 weeks",
          "Home-based elder care — 5 weeks, certified by a nursing tutor",
        ],
        "## Starter grant",
        "Graduates who pass the assessment receive a grant of <strong>Rs. 20,000 to Rs. 45,000</strong> depending on the trade — enough for a machine, a stock of raw materials or a basic tool kit.",
        "## Results",
        "Of 186 people trained since 2022, 118 report regular income from the skill twelve months later. Twenty-two now employ someone else.",
      ]),
      si: html([
        "දන්සල් මාසයකට උදව් වේ; නිපුණතාවක් දශකයකට උදව් වේ. පුහුණුව පමණක් ප්‍රාග්ධනයකින් තොරව ආදායමක් බවට පත් වන්නේ කලාතුරකින් බැවින්, අපි පවත්වන සෑම පාඨමාලාවක්ම ප්‍රායෝගික ඇගයීමකින් සහ ආරම්භක ආධාරයකින් අවසන් වේ.",
        "## 2026 හි පවත්වන පාඨමාලා",
        [
          "කාර්මික මැහුම් — සති 8, සතියකට සවස 3",
          "ආහාර සැකසීම හා ඇසුරුම් කිරීම (ජෑම්, මිරිස් පේස්ට්, කරවල) — සති 6",
          "ජංගම දුරකථන හා කුඩා උපකරණ අලුත්වැඩියාව — සති 10",
          "ඩිජිටල් සාක්ෂරතාව හා මාර්ගගත විකිණීම — සති 6",
          "ත්‍රීරෝද රථ නඩත්තුව හා ආරක්ෂිත රියදුරු — සති 4",
          "නිවසේ සිට වැඩිහිටි රැකවරණය — සති 5, හෙද උපදේශිකාවක් විසින් සහතික කරන",
        ],
        "## ආරම්භක ආධාරය",
        "ඇගයීම සමත් වන උපාධිලාභීන්ට වෘත්තිය අනුව <strong>රු. 20,000 සිට රු. 45,000</strong> දක්වා ආධාරයක් ලැබේ — මැෂිමකට, අමුද්‍රව්‍ය තොගයකට හෝ මූලික මෙවලම් කට්ටලයකට ප්‍රමාණවත්.",
        "## ප්‍රතිඵල",
        "2022 සිට පුහුණු කළ 186 දෙනාගෙන් 118 දෙනෙක් මාස දොළහකට පසු එම නිපුණතාවෙන් නිත්‍ය ආදායමක් ලබන බව වාර්තා කරයි. දෙවිසි දෙනෙක් දැන් වෙනත් අයෙකුට රැකියාව ලබා දෙයි.",
      ]),
      ta: html([
        "இலவச உதவி ஒரு மாதத்திற்கு உதவும்; ஒரு திறன் ஒரு தசாப்தத்திற்கு உதவும். மூலதனமின்றி பயிற்சி மட்டும் அரிதாகவே வருமானமாக மாறுவதால், நாம் நடத்தும் ஒவ்வொரு பாடநெறியும் நடைமுறை மதிப்பீட்டுடனும் தொடக்க உதவியுடனும் நிறைவடைகிறது.",
        "## 2026 இல் வழங்கப்படும் பாடநெறிகள்",
        [
          "தொழிற்சாலைத் தையல் — 8 வாரங்கள், வாரம் 3 மாலைகள்",
          "உணவுப் பதப்படுத்தலும் பொதியிடலும் (ஜாம், மிளகாய் விழுது, கருவாடு) — 6 வாரங்கள்",
          "கைபேசி மற்றும் சிறு உபகரண பழுதுபார்ப்பு — 10 வாரங்கள்",
          "Digital எழுத்தறிவும் இணையவழி விற்பனையும் — 6 வாரங்கள்",
          "முச்சக்கர வண்டி பராமரிப்பும் பாதுகாப்பான ஓட்டுநர் பயிற்சியும் — 4 வாரங்கள்",
          "வீட்டிலிருந்து முதியோர் பராமரிப்பு — 5 வாரங்கள், தாதிய ஆசிரியரால் சான்றளிக்கப்படும்",
        ],
        "## தொடக்க உதவி",
        "மதிப்பீட்டில் தேர்ச்சி பெறுபவர்களுக்கு தொழிலைப் பொறுத்து <strong>ரூ. 20,000 முதல் ரூ. 45,000</strong> வரை உதவி — ஒரு இயந்திரம், மூலப்பொருள் சரக்கு அல்லது அடிப்படைக் கருவித் தொகுப்புக்குப் போதுமானது.",
        "## விளைவுகள்",
        "2022 முதல் பயிற்சி பெற்ற 186 பேரில் 118 பேர் பன்னிரண்டு மாதங்களுக்குப் பின் அந்தத் திறனிலிருந்து நிலையான வருமானம் பெறுவதைத் தெரிவிக்கின்றனர். இருபத்திரண்டு பேர் இப்போது மற்றொருவருக்கு வேலை வழங்குகிறார்கள்.",
      ]),
    },
  },
  {
    slug: "mobile-medical-camps",
    category: "COMMUNITY",
    icon: "Activity",
    coverImage: "/media/medical-camp.svg",
    sortOrder: 10,
    title: tri("Mobile Medical Camps", "සංචාරක වෛද්‍ය කඳවුරු", "நடமாடும் மருத்துவ முகாம்கள்"),
    summary: tri(
      "Free clinics taken to villages without easy access to a hospital — general medicine, eye care, dental and diabetes screening.",
      "රෝහලකට පහසුවෙන් ළඟා විය නොහැකි ගම්වලට ගෙන යන නොමිලේ සායන — සාමාන්‍ය වෛද්‍ය, අක්ෂි, දන්ත සහ දියවැඩියා පරීක්ෂණ.",
      "வைத்தியசாலைக்கு எளிதில் செல்ல முடியாத கிராமங்களுக்கு எடுத்துச் செல்லும் இலவச கிளினிக்குகள் — பொது மருத்துவம், கண், பல் மற்றும் சர்க்கரை பரிசோதனை.",
    ),
    eligibility: tri(
      "Open to everyone in the host village at no cost, regardless of membership.",
      "සාමාජිකත්වය නොසලකා, කඳවුර පවත්වන ගමේ සියලු දෙනාට නොමිලේ විවෘතය.",
      "உறுப்புரிமையைப் பொருட்படுத்தாமல், முகாம் நடக்கும் கிராமத்தின் அனைவருக்கும் இலவசம்.",
    ),
    body: {
      en: html([
        "A hospital forty kilometres away might as well not exist if the bus costs a day's wage. Since 2017 we have run 96 camps and seen just over 21,000 patients.",
        "## What a camp includes",
        [
          "General medicine consultation with two volunteer doctors",
          "Eye screening with free reading glasses dispensed on the day",
          "Dental check and extraction",
          "Blood sugar, blood pressure, haemoglobin and BMI screening",
          "A three-month supply of chronic medication for those already diagnosed",
          "Referral letters, with transport paid for anyone needing hospital follow-up",
        ],
        "## How a location is chosen",
        "We prioritise villages more than ten kilometres from the nearest clinic, estate line rooms, and areas flagged by the public health inspector. Requests from community groups are welcome and go to the health sub-committee.",
        "## Volunteering at a camp",
        "Camps need far more than doctors — registration desks, crowd management, translation between Sinhala and Tamil, pharmacy assistance and transport. No medical training is required for most roles.",
      ]),
      si: html([
        "බස් ගාස්තුව දිනක වේතනයක් වටිනා නම්, කිලෝමීටර් හතළිහක් ඈත රෝහලක් නොතිබුණාට සමානය. 2017 සිට අපි කඳවුරු 96 ක් පවත්වා රෝගීන් 21,000 ට වැඩි ගණනක් බලා ඇත.",
        "## කඳවුරකට ඇතුළත් වන දේ",
        [
          "ස්වේච්ඡා වෛද්‍යවරුන් දෙදෙනෙකු සමඟ සාමාන්‍ය වෛද්‍ය උපදේශනය",
          "එදිනම නොමිලේ කියවීමේ කණ්නාඩි ලබා දෙන අක්ෂි පරීක්ෂණය",
          "දන්ත පරීක්ෂණය සහ දත් ගැලවීම",
          "රුධිර සීනි, රුධිර පීඩනය, හීමොග්ලොබින් සහ BMI පරීක්ෂණ",
          "දැනටමත් හඳුනාගත් අයට මාස තුනක දිගුකාලීන ඖෂධ",
          "රෝහල් පසු විපරම අවශ්‍ය අයට ප්‍රවාහනය ගෙවා දෙන යොමු කිරීමේ ලිපි",
        ],
        "## ස්ථානයක් තෝරන ආකාරය",
        "ළඟම සායනයේ සිට කිලෝමීටර් දහයකට වැඩි දුරින් පිහිටි ගම්, වතු ලයින් කාමර, සහ මහජන සෞඛ්‍ය පරීක්ෂකවරයා විසින් සලකුණු කරන ප්‍රදේශවලට අපි ප්‍රමුඛත්වය දෙමු. ප්‍රජා කණ්ඩායම්වලින් ලැබෙන ඉල්ලීම් සාදරයෙන් පිළිගනු ලබන අතර සෞඛ්‍ය උපකමිටුවට යොමු කෙරේ.",
        "## කඳවුරේ ස්වේච්ඡා සේවය",
        "කඳවුරුවලට වෛද්‍යවරුන්ට වඩා බොහෝ දේ අවශ්‍යයි — ලියාපදිංචි මේස, පිරිස් කළමනාකරණය, සිංහල හා දෙමළ අතර පරිවර්තනය, ඖෂධ සහාය සහ ප්‍රවාහනය. බොහෝ භූමිකා සඳහා වෛද්‍ය පුහුණුවක් අවශ්‍ය නොවේ.",
      ]),
      ta: html([
        "பஸ் கட்டணம் ஒரு நாள் கூலிக்குச் சமமானால், நாற்பது கிலோமீட்டர் தொலைவில் உள்ள வைத்தியசாலை இல்லாததற்குச் சமம். 2017 முதல் நாம் 96 முகாம்களை நடத்தி 21,000 க்கும் மேற்பட்ட நோயாளிகளைப் பரிசோதித்துள்ளோம்.",
        "## ஒரு முகாமில் அடங்குவது",
        [
          "இரு தொண்டர் வைத்தியர்களுடன் பொது மருத்துவ ஆலோசனை",
          "அன்றே இலவச வாசிப்புக் கண்ணாடி வழங்கும் கண் பரிசோதனை",
          "பல் பரிசோதனையும் பல் அகற்றலும்",
          "இரத்தச் சர்க்கரை, இரத்த அழுத்தம், ஹீமோகுளோபின், BMI பரிசோதனை",
          "ஏற்கனவே கண்டறியப்பட்டவர்களுக்கு மூன்று மாத நீண்டகால மருந்து",
          "வைத்தியசாலைத் தொடர் பரிசோதனை தேவைப்படுவோருக்கு போக்குவரத்துடன் பரிந்துரைக் கடிதம்",
        ],
        "## இடம் தேர்ந்தெடுக்கப்படும் விதம்",
        "அருகிலுள்ள கிளினிக்கிலிருந்து பத்து கிலோமீட்டருக்கு மேல் உள்ள கிராமங்கள், தோட்டத் தொழிலாளர் வரிசை அறைகள், பொது சுகாதார பரிசோதகர் சுட்டிக்காட்டும் பகுதிகளுக்கு முன்னுரிமை. சமூகக் குழுக்களின் கோரிக்கைகள் வரவேற்கப்பட்டு சுகாதார உபகுழுவுக்குச் செல்கின்றன.",
        "## முகாமில் தொண்டு சேவை",
        "முகாம்களுக்கு வைத்தியர்களை விட அதிகம் தேவை — பதிவு மேசைகள், கூட்ட நிர்வாகம், சிங்களம்–தமிழ் மொழிபெயர்ப்பு, மருந்தகப் பணி, போக்குவரத்து. பெரும்பாலான பணிகளுக்கு மருத்துவப் பயிற்சி தேவையில்லை.",
      ]),
    },
  },
  {
    slug: "clean-water-and-sanitation",
    category: "COMMUNITY",
    icon: "Droplets",
    coverImage: "/media/water-project.svg",
    sortOrder: 11,
    title: tri("Clean Water & Sanitation", "පිරිසිදු ජලය හා සනීපාරක්ෂාව", "தூய நீரும் சுகாதாரமும்"),
    summary: tri(
      "Tube wells, rainwater harvesting tanks and household toilets for communities with unsafe or distant water sources.",
      "අනාරක්ෂිත හෝ දුරින් පිහිටි ජල මූලාශ්‍ර සහිත ප්‍රජාවන් සඳහා නලකූප, වැසි ජල ටැංකි සහ ගෘහස්ථ වැසිකිළි.",
      "பாதுகாப்பற்ற அல்லது தொலைவில் உள்ள நீர் ஆதாரங்களைக் கொண்ட சமூகங்களுக்கு குழாய்க் கிணறுகள், மழைநீர் தாங்கிகள், வீட்டுக் கழிவறைகள்.",
    ),
    eligibility: tri(
      "Community-level projects selected annually with the Divisional Secretariat and public health inspectors.",
      "ප්‍රාදේශීය ලේකම් කාර්යාලය සහ මහජන සෞඛ්‍ය පරීක්ෂකවරුන් සමඟ වාර්ෂිකව තෝරාගනු ලබන ප්‍රජා මට්ටමේ ව්‍යාපෘති.",
      "பிரதேச செயலகம் மற்றும் பொது சுகாதார பரிசோதகர்களுடன் வருடாந்தம் தேர்ந்தெடுக்கப்படும் சமூக மட்டத் திட்டங்கள்.",
    ),
    body: {
      en: html([
        "Chronic kidney disease of unknown origin, diarrhoeal illness in children and hours lost carrying water all trace back to the same problem. Water is the least glamorous and most effective thing we fund.",
        "## What we build",
        [
          "Tube wells with hand pumps, tested for fluoride and hardness before handover",
          "5,000-litre rainwater harvesting tanks for households and schools",
          "Household toilets with septic tanks, prioritising homes with elderly or disabled members",
          "Filtration units for schools and preschools",
        ],
        "## The community contribution model",
        "Every project requires the community to contribute labour and to form a five-person maintenance committee before construction starts. We supply materials, technical supervision and a two-year spare parts fund. Projects built this way are still working; projects simply handed over are not.",
        "## Completed to date",
        "31 tube wells, 74 rainwater tanks, 112 household toilets and 9 school filtration units, reaching an estimated 4,800 people.",
      ]),
      si: html([
        "නොදන්නා හේතුවෙන් ඇති වන දිගුකාලීන වකුගඩු රෝගය, දරුවන්ගේ පාචන රෝග සහ ජලය ගෙන ඒමට නැති වන පැය ගණන යන සියල්ල එකම ගැටලුවකට යොමු වේ. ජලය අපි අරමුදල් සපයන අවම ආකර්ෂණීය නමුත් වඩාත්ම ඵලදායී දෙයයි.",
        "## අපි ගොඩනගන දේ",
        [
          "භාර දීමට පෙර ෆ්ලෝරයිඩ් හා දෘඩතාව සඳහා පරීක්ෂා කරන ලද අත් පොම්ප සහිත නලකූප",
          "නිවෙස් හා පාසල් සඳහා ලීටර් 5,000 වැසි ජල ටැංකි",
          "වැඩිහිටි හෝ ආබාධිත සාමාජිකයින් සිටින නිවෙස්වලට ප්‍රමුඛත්වය දෙමින්, සෙප්ටික් ටැංකි සහිත ගෘහස්ථ වැසිකිළි",
          "පාසල් හා පෙර පාසල් සඳහා ජල පෙරහන් ඒකක",
        ],
        "## ප්‍රජා දායකත්ව ආකෘතිය",
        "සෑම ව්‍යාපෘතියක්ම ඉදිකිරීම් ආරම්භ වීමට පෙර ප්‍රජාව ශ්‍රමය දායක කිරීම සහ පස් දෙනෙකුගෙන් යුත් නඩත්තු කමිටුවක් පිහිටුවීම අවශ්‍ය කරයි. අපි ද්‍රව්‍ය, තාක්ෂණික අධීක්ෂණය සහ වර්ෂ දෙකක අමතර කොටස් අරමුදලක් සපයමු. මෙම ආකාරයට ගොඩනගන ලද ව්‍යාපෘති තවමත් ක්‍රියාත්මකයි; හුදෙක් භාර දෙන ලද ව්‍යාපෘති එසේ නොවේ.",
        "## මේ දක්වා සම්පූර්ණ කළ",
        "නලකූප 31, වැසි ජල ටැංකි 74, ගෘහස්ථ වැසිකිළි 112 සහ පාසල් පෙරහන් ඒකක 9, ඇස්තමේන්තුගත පුද්ගලයින් 4,800 ට ළඟා වී ඇත.",
      ]),
      ta: html([
        "காரணம் அறியப்படாத நீண்டகால சிறுநீரக நோய், குழந்தைகளின் வயிற்றுப்போக்கு, நீர் எடுத்துவரக் இழக்கும் மணிநேரங்கள் — அனைத்தும் ஒரே பிரச்சினையையே சுட்டுகின்றன. நீர் என்பது நாம் நிதியளிக்கும் மிகக் குறைந்த கவர்ச்சியான, ஆனால் மிக பயனுள்ள விடயம்.",
        "## நாம் அமைப்பது",
        [
          "ஒப்படைப்பதற்கு முன் புளோரைடு மற்றும் கடினத்தன்மை பரிசோதிக்கப்பட்ட கைப் பம்பு குழாய்க் கிணறுகள்",
          "வீடுகளுக்கும் பாடசாலைகளுக்கும் 5,000 லீட்டர் மழைநீர் தாங்கிகள்",
          "முதியோர் அல்லது மாற்றுத்திறனாளிகள் உள்ள வீடுகளுக்கு முன்னுரிமையுடன், செப்டிக் தாங்கியுடன் வீட்டுக் கழிவறைகள்",
          "பாடசாலைகளுக்கும் முன்பள்ளிகளுக்கும் நீர் வடிகட்டி அலகுகள்",
        ],
        "## சமூகப் பங்களிப்பு மாதிரி",
        "ஒவ்வொரு திட்டமும் கட்டுமானம் தொடங்கும் முன் சமூகம் உழைப்பைப் பங்களிக்கவும், ஐந்து பேர் கொண்ட பராமரிப்புக் குழுவை அமைக்கவும் கோருகிறது. நாம் பொருட்கள், தொழில்நுட்ப மேற்பார்வை, இரு வருட உதிரிபாகங்கள் நிதியம் வழங்குகிறோம். இவ்வாறு கட்டப்பட்ட திட்டங்கள் இன்னும் இயங்குகின்றன; வெறுமனே ஒப்படைக்கப்பட்டவை இயங்கவில்லை.",
        "## இதுவரை நிறைவடைந்தவை",
        "31 குழாய்க் கிணறுகள், 74 மழைநீர் தாங்கிகள், 112 வீட்டுக் கழிவறைகள், 9 பாடசாலை வடிகட்டி அலகுகள் — சுமார் 4,800 பேரைச் சென்றடைந்துள்ளன.",
      ]),
    },
  },
];

export type ProjectSeed = {
  slug: string;
  location: string;
  targetAmount: number;
  raisedAmount: number;
  spentAmount: number;
  beneficiaries: number;
  status: "PLANNED" | "ONGOING" | "COMPLETED";
  startedDaysAgo: number;
  completedDaysAgo?: number;
  coverImage: string;
  title: Tri;
  summary: Tri;
  body: Tri;
};

export const PROJECTS: ProjectSeed[] = [
  {
    slug: "sarana-housing-2026",
    location: "Homagama, Colombo District",
    targetAmount: 4_800_000,
    raisedAmount: 3_140_000,
    spentAmount: 2_460_000,
    beneficiaries: 12,
    status: "ONGOING",
    startedDaysAgo: 240,
    coverImage: "/media/housing-project.svg",
    title: tri("Sarana Housing Project", "සරණ නිවාස ව්‍යාපෘතිය", "சரண வீடமைப்புத் திட்டம்"),
    summary: tri(
      "Rebuilding twelve homes for families living under temporary roofing after the 2025 floods.",
      "2025 ගංවතුරෙන් පසු තාවකාලික සෙවිලි යට ජීවත් වන පවුල් සඳහා නිවෙස් දොළහක් නැවත ගොඩනැගීම.",
      "2025 வெள்ளத்திற்குப் பின் தற்காலிக கூரையின் கீழ் வாழும் குடும்பங்களுக்கு பன்னிரண்டு வீடுகளை மீள்கட்டுதல்.",
    ),
    body: {
      en: html([
        "After the May 2025 floods, 34 families in the Homagama division were left with houses that could not be repaired. The state resettlement grant covered foundations and walls for most, but twelve families — all headed by a widow, a person with a disability or an elderly couple — could not raise the balance.",
        "## Scope",
        [
          "Twelve two-room brick houses with a tiled roof, toilet and water connection",
          "Electricity connection and basic wiring",
          "A rainwater tank per house",
        ],
        "## Progress",
        "Seven houses are complete and occupied. Three are at roofing stage. Two are awaiting the release of the second tranche of funds. All construction is supervised by a volunteer civil engineer, and every payment is against a measured bill of quantities.",
        "## What is still needed",
        "Rs. 1.66 million to complete the final five houses. Material donations — cement, roofing sheets, tiles and doors — are welcome and are valued at market rate in our accounts.",
      ]),
      si: html([
        "2025 මැයි ගංවතුරෙන් පසු හෝමාගම කොට්ඨාසයේ පවුල් 34 ක් අලුත්වැඩියා කළ නොහැකි නිවෙස්වලින් ඉතිරි විය. රාජ්‍ය නැවත පදිංචි කිරීමේ ආධාරය බොහෝ දෙනාට අත්තිවාරම් සහ බිත්ති සඳහා ප්‍රමාණවත් වූ නමුත්, පවුල් දොළහකට — සියල්ලම වැන්දඹුවක්, ආබාධිත පුද්ගලයෙකු හෝ වයස්ගත යුවළක් විසින් නායකත්වය දෙන — ඉතිරි මුදල සොයා ගත නොහැකි විය.",
        "## විෂය පථය",
        [
          "උළු වහලයක්, වැසිකිළියක් සහ ජල සම්බන්ධතාවක් සහිත කාමර දෙකේ ගඩොල් නිවෙස් දොළහක්",
          "විදුලි සම්බන්ධතාව සහ මූලික වයරින්",
          "නිවසකට එක් වැසි ජල ටැංකියක්",
        ],
        "## ප්‍රගතිය",
        "නිවෙස් හතක් සම්පූර්ණ කර පදිංචි වී ඇත. තුනක් වහල අදියරේ පවතී. දෙකක් අරමුදල්වල දෙවන කොටස නිදහස් කරන තුරු බලා සිටී. සියලු ඉදිකිරීම් ස්වේච්ඡා සිවිල් ඉංජිනේරුවෙකු විසින් අධීක්ෂණය කරන අතර, සෑම ගෙවීමක්ම මනින ලද ප්‍රමාණ බිල්පතකට එරෙහිව සිදු වේ.",
        "## තවමත් අවශ්‍ය දේ",
        "අවසන් නිවෙස් පහ සම්පූර්ණ කිරීමට රු. මිලියන 1.66 ක්. ද්‍රව්‍ය පරිත්‍යාග — සිමෙන්ති, වහල තහඩු, උළු සහ දොරවල් — සාදරයෙන් පිළිගනු ලබන අතර අපගේ ගිණුම්වල වෙළඳපොල මිලට අගය කෙරේ.",
      ]),
      ta: html([
        "2025 மே வெள்ளத்திற்குப் பின், ஹோமாகம பிரிவில் 34 குடும்பங்கள் பழுதுபார்க்க முடியாத வீடுகளுடன் விடப்பட்டன. அரச மீள்குடியேற்ற உதவி பெரும்பாலானோருக்கு அடித்தளமும் சுவரும் ஈடுசெய்தது, ஆனால் பன்னிரண்டு குடும்பங்களால் — அனைத்தும் விதவை, மாற்றுத்திறனாளி அல்லது முதியோர் தம்பதியால் நடத்தப்படுவன — மீதித் தொகையைத் திரட்ட முடியவில்லை.",
        "## திட்ட எல்லை",
        [
          "ஓட்டுக் கூரை, கழிவறை, நீர் இணைப்புடன் இரண்டு அறை செங்கல் வீடுகள் பன்னிரண்டு",
          "மின் இணைப்பும் அடிப்படை கம்பி அமைப்பும்",
          "ஒரு வீட்டுக்கு ஒரு மழைநீர் தாங்கி",
        ],
        "## முன்னேற்றம்",
        "ஏழு வீடுகள் நிறைவடைந்து குடியேறப்பட்டுள்ளன. மூன்று கூரை நிலையில். இரண்டு நிதியின் இரண்டாம் தவணை விடுவிப்பை எதிர்நோக்கியுள்ளன. அனைத்துக் கட்டுமானமும் தொண்டர் சிவில் பொறியியலாளரால் மேற்பார்வை செய்யப்படுகிறது, ஒவ்வொரு கட்டணமும் அளவிடப்பட்ட அளவுப் பட்டியலுக்கு எதிராகவே.",
        "## இன்னும் தேவைப்படுவது",
        "இறுதி ஐந்து வீடுகளை நிறைவு செய்ய ரூ. 1.66 மில்லியன். பொருள் நன்கொடைகள் — சீமெந்து, கூரைத் தகடு, ஓடு, கதவுகள் — வரவேற்கப்படுகின்றன, எமது கணக்குகளில் சந்தை விலையில் மதிப்பிடப்படும்.",
      ]),
    },
  },
  {
    slug: "diyawara-water-project",
    location: "Kekirawa, Anuradhapura District",
    targetAmount: 2_600_000,
    raisedAmount: 2_600_000,
    spentAmount: 2_512_000,
    beneficiaries: 640,
    status: "COMPLETED",
    startedDaysAgo: 520,
    completedDaysAgo: 95,
    coverImage: "/media/water-project.svg",
    title: tri("Diyawara Clean Water Project", "දියවර පිරිසිදු ජල ව්‍යාපෘතිය", "தியவர தூய நீர்த் திட்டம்"),
    summary: tri(
      "Eight tube wells and a school filtration plant in a chronic kidney disease affected area.",
      "දිගුකාලීන වකුගඩු රෝගය පවතින ප්‍රදේශයක නලකූප අටක් සහ පාසල් ජල පෙරහන් යන්ත්‍රාගාරයක්.",
      "நீண்டகால சிறுநீரக நோய் பாதித்த பகுதியில் எட்டு குழாய்க் கிணறுகளும் பாடசாலை வடிகட்டி நிலையமும்.",
    ),
    body: {
      en: html([
        "Kekirawa sits inside Sri Lanka's chronic kidney disease belt. Three villages in the division were drawing drinking water from shallow agricultural wells with high hardness and fluoride readings.",
        "## What was built",
        [
          "Eight deep tube wells with hand pumps, all tested and certified by the National Water Supply Board",
          "A reverse-osmosis filtration plant at Kekirawa Maha Vidyalaya serving 410 students",
          "Three community water collection points with concrete aprons and drainage",
          "A five-person maintenance committee per well, trained and issued a tool kit",
        ],
        "## Outcome twelve months on",
        "All eight wells are functioning. The public health inspector's follow-up survey recorded a 71% fall in reported diarrhoeal illness among children under five in the served villages.",
        "## Accounts",
        "Total spend Rs. 2,512,000 against a budget of Rs. 2,600,000. The Rs. 88,000 balance was transferred to the spare parts fund for the wells, as approved at the 2025 annual general meeting.",
      ]),
      si: html([
        "කැකිරාව පිහිටා ඇත්තේ ශ්‍රී ලංකාවේ දිගුකාලීන වකුගඩු රෝග කලාපය තුළය. එම කොට්ඨාසයේ ගම් තුනක් ඉහළ දෘඩතාව සහ ෆ්ලෝරයිඩ් අන්තර්ගතයක් සහිත නොගැඹුරු කෘෂිකාර්මික ළිංවලින් පානීය ජලය ලබා ගත්තේය.",
        "## ගොඩනගන ලද දේ",
        [
          "ජාතික ජල සම්පාදන මණ්ඩලය විසින් පරීක්ෂා කර සහතික කරන ලද අත් පොම්ප සහිත ගැඹුරු නලකූප අටක්",
          "සිසුන් 410 කට සේවය කරන කැකිරාව මහා විද්‍යාලයේ ප්‍රතිලෝම ආස්මෝසිස් පෙරහන් යන්ත්‍රාගාරයක්",
          "කොන්ක්‍රීට් මිදුල් සහ ජලාපවහන සහිත ප්‍රජා ජල එකතු කිරීමේ ස්ථාන තුනක්",
          "ළිඳකට පස් දෙනෙකුගෙන් යුත් නඩත්තු කමිටුවක්, පුහුණු කර මෙවලම් කට්ටලයක් ලබා දී ඇත",
        ],
        "## මාස දොළහකට පසු ප්‍රතිඵලය",
        "සියලු ළිං අටම ක්‍රියාත්මකයි. මහජන සෞඛ්‍ය පරීක්ෂකවරයාගේ පසු විපරම් සමීක්ෂණයේ, සේවය ලබන ගම්වල වයස පහට අඩු දරුවන් අතර වාර්තා වූ පාචන රෝග 71% කින් අඩු වී ඇති බව සටහන් විය.",
        "## ගිණුම්",
        "රු. 2,600,000 ක අයවැයට එරෙහිව මුළු වියදම රු. 2,512,000 කි. රු. 88,000 ශේෂය 2025 වාර්ෂික මහා සභා රැස්වීමේදී අනුමත කළ පරිදි ළිං සඳහා අමතර කොටස් අරමුදලට මාරු කරන ලදී.",
      ]),
      ta: html([
        "கெகிராவ இலங்கையின் நீண்டகால சிறுநீரக நோய் வளையத்தில் அமைந்துள்ளது. அந்தப் பிரிவின் மூன்று கிராமங்கள் அதிக கடினத்தன்மையும் புளோரைடும் கொண்ட ஆழமற்ற விவசாயக் கிணறுகளிலிருந்து குடிநீர் பெற்றன.",
        "## அமைக்கப்பட்டவை",
        [
          "தேசிய நீர் வழங்கல் சபையால் பரிசோதித்து சான்றளிக்கப்பட்ட கைப் பம்புடன் எட்டு ஆழ் குழாய்க் கிணறுகள்",
          "410 மாணவர்களுக்குச் சேவை செய்யும் கெகிராவ மகா வித்தியாலயத்தில் ரிவர்ஸ் ஓஸ்மோசிஸ் வடிகட்டி நிலையம்",
          "கொங்கிரீட் தளமும் வடிகாலும் கொண்ட மூன்று சமூக நீர் சேகரிப்பு நிலையங்கள்",
          "ஒரு கிணறுக்கு ஐந்து பேர் கொண்ட பராமரிப்புக் குழு, பயிற்சியும் கருவித் தொகுப்பும் வழங்கப்பட்டது",
        ],
        "## பன்னிரண்டு மாதங்களுக்குப் பின் விளைவு",
        "எட்டுக் கிணறுகளும் இயங்குகின்றன. பொது சுகாதார பரிசோதகரின் தொடர் ஆய்வில், சேவை பெறும் கிராமங்களில் ஐந்து வயதுக்குக் குறைந்த குழந்தைகளிடையே தெரிவிக்கப்பட்ட வயிற்றுப்போக்கு நோய் 71% குறைந்துள்ளது பதிவாகியது.",
        "## கணக்குகள்",
        "ரூ. 2,600,000 வரவுசெலவுத் திட்டத்திற்கு எதிராக மொத்தச் செலவு ரூ. 2,512,000. ரூ. 88,000 மீதி 2025 வருடாந்த பொதுக் கூட்டத்தில் அனுமதிக்கப்பட்டபடி கிணறுகளுக்கான உதிரிபாகங்கள் நிதியத்திற்கு மாற்றப்பட்டது.",
      ]),
    },
  },
  {
    slug: "pahana-scholarship-fund",
    location: "All districts served",
    targetAmount: 6_000_000,
    raisedAmount: 4_320_000,
    spentAmount: 3_960_000,
    beneficiaries: 96,
    status: "ONGOING",
    startedDaysAgo: 400,
    coverImage: "/media/kids-education.svg",
    title: tri("Pahana Scholarship Fund", "පහන ශිෂ්‍යත්ව අරමුදල", "பஹன உதவித்தொகை நிதியம்"),
    summary: tri(
      "An endowment that funds 96 scholarships a year without drawing on the general welfare fund.",
      "සාමාන්‍ය සුබසාධක අරමුදලෙන් ලබා නොගෙන වර්ෂයකට ශිෂ්‍යත්ව 96 ක් සඳහා අරමුදල් සපයන පදනම් අරමුදලක්.",
      "பொது நலன்புரி நிதியத்திலிருந்து எடுக்காமல் ஆண்டுக்கு 96 உதவித்தொகைகளுக்கு நிதியளிக்கும் நிரந்தர நிதியம்.",
    ),
    body: {
      en: html([
        "Scholarships used to compete with medical claims for the same rupees. The Pahana fund separates them permanently: a ring-fenced endowment whose annual return pays the awards, so a bad year for donations never costs a child their school year.",
        "## Structure",
        "Capital is held in a fixed deposit and government securities. Only the annual return is spent. The capital is never touched without a two-thirds vote at a general meeting.",
        "## Current position",
        [
          "Endowment capital: <strong>Rs. 4.32 million</strong> of a <strong>Rs. 6 million</strong> target",
          "Awards funded in the current academic year: <strong>96</strong>",
          "Cost per award, all categories averaged: <strong>Rs. 41,250</strong>",
        ],
        "## Named scholarships",
        "A contribution of Rs. 500,000 endows a named scholarship in perpetuity — in your name or in memory of someone. Four have been established so far. Talk to the treasurer if this interests you.",
      ]),
      si: html([
        "ශිෂ්‍යත්ව එකම රුපියල් සඳහා වෛද්‍ය ඉල්ලීම් සමඟ තරඟ කළේය. පහන අරමුදල ඒවා ස්ථිරව වෙන් කරයි: වාර්ෂික ප්‍රතිලාභය ප්‍රදාන ගෙවන වෙන් කරන ලද පදනමක් නිසා, පරිත්‍යාග අඩු වර්ෂයක් කිසිදු දරුවෙකුට තම පාසල් වර්ෂය අහිමි නොකරයි.",
        "## ව්‍යුහය",
        "ප්‍රාග්ධනය ස්ථාවර තැන්පතුවක සහ රාජ්‍ය සුරැකුම්පත්වල තබා ඇත. වියදම් කරන්නේ වාර්ෂික ප්‍රතිලාභය පමණි. මහා සභා රැස්වීමේ තුනෙන් දෙකක ඡන්දයකින් තොරව ප්‍රාග්ධනය කිසිවිටෙකත් ස්පර්ශ නොකෙරේ.",
        "## වර්තමාන තත්ත්වය",
        [
          "පදනම් ප්‍රාග්ධනය: <strong>රු. මිලියන 6</strong> ඉලක්කයෙන් <strong>රු. මිලියන 4.32</strong>",
          "වර්තමාන අධ්‍යයන වර්ෂයේ අරමුදල් සපයන ප්‍රදාන: <strong>96</strong>",
          "සියලු වර්ග සාමාන්‍යගත ප්‍රදානයකට පිරිවැය: <strong>රු. 41,250</strong>",
        ],
        "## නම් කරන ලද ශිෂ්‍යත්ව",
        "රු. 500,000 ක දායකත්වයක් සදාකාලිකව නම් කරන ලද ශිෂ්‍යත්වයක් පිහිටුවයි — ඔබේ නමින් හෝ කිසිවෙකුගේ සිහිවටනයක් ලෙස. මේ දක්වා හතරක් පිහිටුවා ඇත. මේ ගැන උනන්දුවක් ඇත්නම් භාණ්ඩාගාරික සමඟ කතා කරන්න.",
      ]),
      ta: html([
        "உதவித்தொகைகள் அதே ரூபாய்களுக்காக மருத்துவ கோரிக்கைகளுடன் போட்டியிட்டன. பஹன நிதியம் அவற்றை நிரந்தரமாகப் பிரிக்கிறது: வருடாந்த வருவாய் விருதுகளைச் செலுத்தும் தனிமைப்படுத்தப்பட்ட நிரந்தர நிதியம், எனவே நன்கொடைகள் குறைந்த ஆண்டு எந்தப் பிள்ளையின் கல்வியாண்டையும் பாதிக்காது.",
        "## கட்டமைப்பு",
        "மூலதனம் நிலையான வைப்பிலும் அரச பிணையங்களிலும் வைக்கப்பட்டுள்ளது. வருடாந்த வருவாய் மட்டுமே செலவிடப்படுகிறது. பொதுக் கூட்டத்தில் மூன்றில் இரண்டு வாக்கின்றி மூலதனம் தொடப்படுவதில்லை.",
        "## தற்போதைய நிலை",
        [
          "நிரந்தர நிதி மூலதனம்: <strong>ரூ. 6 மில்லியன்</strong> இலக்கில் <strong>ரூ. 4.32 மில்லியன்</strong>",
          "நடப்புக் கல்வியாண்டில் நிதியளிக்கப்பட்ட விருதுகள்: <strong>96</strong>",
          "அனைத்து வகைகளின் சராசரி ஒரு விருதுக்கான செலவு: <strong>ரூ. 41,250</strong>",
        ],
        "## பெயரிடப்பட்ட உதவித்தொகைகள்",
        "ரூ. 500,000 பங்களிப்பு நிரந்தரமாக ஒரு பெயரிடப்பட்ட உதவித்தொகையை நிறுவுகிறது — உங்கள் பெயரில் அல்லது ஒருவரின் நினைவாக. இதுவரை நான்கு நிறுவப்பட்டுள்ளன. ஆர்வம் இருந்தால் பொருளாளருடன் பேசுங்கள்.",
      ]),
    },
  },
  {
    slug: "community-hall-renovation",
    location: "Nugegoda, Colombo District",
    targetAmount: 1_900_000,
    raisedAmount: 1_240_000,
    spentAmount: 980_000,
    beneficiaries: 1840,
    status: "ONGOING",
    startedDaysAgo: 150,
    coverImage: "/media/community-hall.svg",
    title: tri("Community Hall Renovation", "ප්‍රජා ශාලා පුනරුත්ථාපනය", "சமூக மண்டப புனரமைப்பு"),
    summary: tri(
      "Rebuilding the association hall used for the elders' day centre, training courses and the annual general meeting.",
      "වැඩිහිටි දිවා මධ්‍යස්ථානය, පුහුණු පාඨමාලා සහ වාර්ෂික මහා සභාව සඳහා භාවිත වන සමිති ශාලාව නැවත ගොඩනැගීම.",
      "முதியோர் பகல் நிலையம், பயிற்சி பாடநெறிகள், வருடாந்த பொதுக் கூட்டம் ஆகியவற்றுக்குப் பயன்படும் சங்க மண்டபத்தை மீள்கட்டுதல்.",
    ),
    body: {
      en: html([
        "The hall is the association's only fixed asset and it is working far beyond what it was built for in 1998 — a day centre on Wednesdays, six training courses a week, the fortnightly welfare committee and the AGM.",
        "## Works in scope",
        [
          "Roof replacement and ceiling — leaking since 2023",
          "Accessible toilet and a ramp at the main entrance",
          "Rewiring to current standards, with LED lighting throughout",
          "A partition to create a second training room",
          "A small kitchen for the day centre lunch service",
        ],
        "## Why it matters",
        "Two of the six training courses currently run in rented rooms at Rs. 18,000 a month. Completing the partition removes that cost permanently and pays for itself in under three years.",
        "## Progress",
        "Roof and ceiling complete. Rewiring 60% done. The accessible toilet and ramp are next, and are the priority the elders' committee asked for.",
      ]),
      si: html([
        "ශාලාව සමිතියේ එකම ස්ථාවර වත්කම වන අතර, 1998 දී එය ගොඩනගන ලද අරමුණට වඩා බොහෝ දුරට ක්‍රියාත්මක වේ — බදාදා දිවා මධ්‍යස්ථානය, සතියකට පුහුණු පාඨමාලා හයක්, සති දෙකකට වරක් සුබසාධක කමිටුව සහ වාර්ෂික මහා සභාව.",
        "## විෂය පථයේ කටයුතු",
        [
          "වහල හා තට්ටු ප්‍රතිස්ථාපනය — 2023 සිට ජලය කාන්දු වේ",
          "ප්‍රවේශ්‍ය වැසිකිළියක් සහ ප්‍රධාන දොරටුවේ ආනතියක්",
          "වර්තමාන ප්‍රමිතීන්ට වයරින් නැවත සකස් කිරීම, පුරාවට LED ආලෝකකරණය සමඟ",
          "දෙවන පුහුණු කාමරයක් සෑදීමට බෙදුම් තිරයක්",
          "දිවා මධ්‍යස්ථාන දිවා ආහාර සේවය සඳහා කුඩා මුළුතැන්ගෙයක්",
        ],
        "## එය වැදගත් වන්නේ ඇයි",
        "පුහුණු පාඨමාලා හයෙන් දෙකක් දැනට මසකට රු. 18,000 ට කුලියට ගත් කාමරවල පවත්වනු ලැබේ. බෙදුම් තිරය සම්පූර්ණ කිරීම එම වියදම ස්ථිරව ඉවත් කරන අතර වර්ෂ තුනකට අඩු කාලයකින් තමා වෙනුවෙන් ගෙවා ගනී.",
        "## ප්‍රගතිය",
        "වහල හා තට්ටුව සම්පූර්ණ. වයරින් 60% නිම. ප්‍රවේශ්‍ය වැසිකිළිය සහ ආනතිය ඊළඟට, එය වැඩිහිටි කමිටුව ඉල්ලා සිටි ප්‍රමුඛතාවයයි.",
      ]),
      ta: html([
        "மண்டபம் சங்கத்தின் ஒரே நிலையான சொத்து, 1998 இல் கட்டப்பட்ட நோக்கத்திற்கு மேலாக இயங்குகிறது — புதன்கிழமை பகல் நிலையம், வாரம் ஆறு பயிற்சி பாடநெறிகள், இரு வாரங்களுக்கு ஒரு நலன்புரிக் குழு, வருடாந்த பொதுக் கூட்டம்.",
        "## திட்ட எல்லையிலான பணிகள்",
        [
          "கூரை மற்றும் உட்கூரை மாற்றம் — 2023 முதல் நீர் கசிவு",
          "அணுகக்கூடிய கழிவறையும் முதன்மை நுழைவாயிலில் சாய்தளமும்",
          "தற்போதைய தரத்திற்கு மின்கம்பி மாற்றம், முழுவதும் LED விளக்குகள்",
          "இரண்டாம் பயிற்சி அறையை உருவாக்கும் பிரிப்புச் சுவர்",
          "பகல் நிலைய மதிய உணவுச் சேவைக்கு சிறு சமையலறை",
        ],
        "## இது முக்கியமானது ஏன்",
        "ஆறு பயிற்சி பாடநெறிகளில் இரண்டு தற்போது மாதம் ரூ. 18,000 வாடகை அறைகளில் நடக்கிறது. பிரிப்புச் சுவரை நிறைவு செய்வது அந்தச் செலவை நிரந்தரமாக நீக்கி மூன்று ஆண்டுகளுக்குள் தன்னைச் சரிக்கட்டும்.",
        "## முன்னேற்றம்",
        "கூரையும் உட்கூரையும் நிறைவு. மின்கம்பி மாற்றம் 60% முடிந்தது. அணுகக்கூடிய கழிவறையும் சாய்தளமும் அடுத்தது, அதுவே முதியோர் குழு கேட்ட முன்னுரிமை.",
      ]),
    },
  },
  {
    slug: "sisu-nutrition-programme",
    location: "Hatton & Talawakele, Nuwara Eliya District",
    targetAmount: 3_200_000,
    raisedAmount: 1_680_000,
    spentAmount: 1_420_000,
    beneficiaries: 340,
    status: "ONGOING",
    startedDaysAgo: 300,
    coverImage: "/media/school-supplies.svg",
    title: tri("Sisu Nutrition Programme", "සිසු පෝෂණ වැඩසටහන", "சிசு ஊட்டச்சத்துத் திட்டம்"),
    summary: tri(
      "A morning meal and monthly growth monitoring for 340 estate-sector children identified as underweight.",
      "අඩු බරින් යුතු ලෙස හඳුනාගත් වතු අංශයේ දරුවන් 340 දෙනෙකුට උදෑසන ආහාරයක් සහ මාසික වර්ධන නිරීක්ෂණය.",
      "எடை குறைவாக அடையாளம் காணப்பட்ட 340 தோட்டப் பகுதிக் குழந்தைகளுக்கு காலை உணவும் மாதாந்த வளர்ச்சிக் கண்காணிப்பும்.",
    ),
    body: {
      en: html([
        "In the two estate divisions we work in, the medical officer of health recorded 31% of children under twelve as underweight for their age — more than double the national figure.",
        "## What the programme provides",
        [
          "A fortified morning meal on every school day, cooked at the school by paid local mothers",
          "Monthly weight and height measurement, recorded in a shared register with the MOH office",
          "Deworming and iron supplementation twice yearly through the MOH",
          "Nutrition sessions for parents, held in Tamil, on cooking cheaply and well",
        ],
        "## Results after nine months",
        "Of 340 children enrolled, 214 have moved out of the underweight category. School attendance in the two schools rose from 79% to 91%.",
        "## Cost",
        "Rs. 78 per child per school day, including the cooks' wages. A donation of Rs. 15,000 feeds one child for a full school year.",
      ]),
      si: html([
        "අපි කටයුතු කරන වතු කොට්ඨාස දෙකේ, සෞඛ්‍ය වෛද්‍ය නිලධාරියා වයස දොළහට අඩු දරුවන්ගෙන් 31% ක් තම වයසට අඩු බර ලෙස සටහන් කළේය — ජාතික අගයට වඩා දෙගුණයකට වැඩි.",
        "## වැඩසටහන සපයන දේ",
        [
          "සෑම පාසල් දිනකම, ගෙවීම් ලබන ප්‍රාදේශීය මව්වරුන් විසින් පාසලේ පිසින ශක්තිමත් කළ උදෑසන ආහාරයක්",
          "මාසිකව බර සහ උස මැනීම, සෞඛ්‍ය වෛද්‍ය කාර්යාලය සමඟ බෙදාගත් ලේඛනයේ සටහන් කරයි",
          "සෞඛ්‍ය වෛද්‍ය කාර්යාලය හරහා වර්ෂයකට දෙවරක් පණු ඖෂධ සහ යකඩ අතිරේක",
          "අඩු වියදමින් හොඳින් පිසීම පිළිබඳ, දෙමළ භාෂාවෙන් දෙමාපියන් සඳහා පෝෂණ සැසි",
        ],
        "## මාස නවයකට පසු ප්‍රතිඵල",
        "ලියාපදිංචි වූ දරුවන් 340 දෙනාගෙන් 214 දෙනෙක් අඩු බර වර්ගයෙන් ඉවත් වී ඇත. එම පාසල් දෙකේ පැමිණීම 79% සිට 91% දක්වා ඉහළ ගියේය.",
        "## පිරිවැය",
        "පිසන්නන්ගේ වේතනය ඇතුළුව, පාසල් දිනකට දරුවෙකුට රු. 78 කි. රු. 15,000 ක පරිත්‍යාගයක් එක් දරුවෙකුට සම්පූර්ණ පාසල් වර්ෂයක් පෝෂණය කරයි.",
      ]),
      ta: html([
        "நாம் செயற்படும் இரு தோட்டப் பிரிவுகளில், சுகாதார வைத்திய அதிகாரி பன்னிரண்டு வயதுக்குக் குறைந்த குழந்தைகளில் 31% வயதுக்கேற்ற எடையின்றி இருப்பதைப் பதிவு செய்தார் — தேசிய சராசரியை விட இரு மடங்குக்கு மேல்.",
        "## திட்டம் வழங்குவது",
        [
          "ஒவ்வொரு பாடசாலை நாளிலும், ஊதியம் பெறும் உள்ளூர் தாய்மார்களால் பாடசாலையில் சமைக்கப்படும் ஊட்டச்சத்து நிரப்பிய காலை உணவு",
          "மாதாந்த எடை மற்றும் உயர அளவீடு, MOH அலுவலகத்துடன் பங்கிடப்பட்ட பதிவேட்டில் பதிவு",
          "MOH வழியாக ஆண்டுக்கு இருமுறை புழு நீக்கமும் இரும்புச்சத்து நிரப்பலும்",
          "குறைந்த செலவில் நன்றாகச் சமைப்பது பற்றி, தமிழில் பெற்றோருக்கு ஊட்டச்சத்து அமர்வுகள்",
        ],
        "## ஒன்பது மாதங்களுக்குப் பின் விளைவுகள்",
        "சேர்க்கப்பட்ட 340 குழந்தைகளில் 214 பேர் எடை குறைவு பிரிவிலிருந்து வெளியேறியுள்ளனர். இரு பாடசாலைகளின் வருகை 79% இலிருந்து 91% ஆக உயர்ந்தது.",
        "## செலவு",
        "சமையல்காரர்களின் ஊதியம் உட்பட, ஒரு பாடசாலை நாளுக்கு ஒரு குழந்தைக்கு ரூ. 78. ரூ. 15,000 நன்கொடை ஒரு குழந்தையை முழுக் கல்வியாண்டுக்கு ஊட்டுகிறது.",
      ]),
    },
  },
  {
    slug: "digital-literacy-centre",
    location: "Kalmunai, Ampara District",
    targetAmount: 2_100_000,
    raisedAmount: 420_000,
    spentAmount: 0,
    beneficiaries: 0,
    status: "PLANNED",
    startedDaysAgo: 20,
    coverImage: "/media/volunteer-training.svg",
    title: tri("Digital Literacy Centre", "ඩිජිටල් සාක්ෂරතා මධ්‍යස්ථානය", "Digital எழுத்தறிவு நிலையம்"),
    summary: tri(
      "A twelve-station computer centre offering free evening classes and a supervised space for online work.",
      "නොමිලේ සවස පන්ති සහ මාර්ගගත වැඩ සඳහා අධීක්ෂිත ඉඩක් සපයන දොළොස් ස්ථානයක පරිගණක මධ්‍යස්ථානයක්.",
      "இலவச மாலை வகுப்புகளும் இணையவழி வேலைக்கான மேற்பார்வையிடப்பட்ட இடமும் வழங்கும் பன்னிரண்டு நிலைய கணினி நிலையம்.",
    ),
    body: {
      en: html([
        "Young people in Kalmunai can find remote freelance work — data entry, transcription, graphic design — but not a reliable computer and connection to do it from. This centre is a direct response to a request from the local youth society.",
        "## Planned facilities",
        [
          "Twelve refurbished desktop workstations with fibre connection and a backup inverter",
          "A printer, scanner and document station for public use at cost",
          "Free evening classes: basic computing, spreadsheets, online selling and freelancing platforms",
          "Supervised open access from 4 p.m. to 9 p.m., free for members and students",
        ],
        "## Status",
        "Rs. 420,000 raised of a Rs. 2.1 million target. A local business has offered the ground-floor space rent-free for three years, which removes the largest recurring cost. Construction will begin when 60% of the target is reached.",
        "## How to help",
        "We need refurbished computers no more than five years old, monitors, a UPS, and two volunteer instructors who can teach in Tamil.",
      ]),
      si: html([
        "කල්මුනේ තරුණයින්ට දුරස්ථ නිදහස් රැකියා සොයාගත හැක — දත්ත ඇතුළත් කිරීම, පිටපත් කිරීම, ග්‍රැෆික් නිර්මාණ — නමුත් එය කිරීමට විශ්වාසනීය පරිගණකයක් සහ සම්බන්ධතාවක් නොමැත. මෙම මධ්‍යස්ථානය ප්‍රාදේශීය තරුණ සමිතියේ ඉල්ලීමකට සෘජු ප්‍රතිචාරයකි.",
        "## සැලසුම් කළ පහසුකම්",
        [
          "ෆයිබර් සම්බන්ධතාව සහ උපස්ථ ඉන්වර්ටරයක් සමඟ ප්‍රතිසංස්කරණය කළ ඩෙස්ක්ටොප් ස්ථාන දොළහක්",
          "පිරිවැය මිලට මහජන භාවිතය සඳහා මුද්‍රණ යන්ත්‍රයක්, ස්කෑනරයක් සහ ලේඛන ස්ථානයක්",
          "නොමිලේ සවස පන්ති: මූලික පරිගණකකරණය, පැතුරුම්පත්, මාර්ගගත විකිණීම සහ නිදහස් රැකියා වේදිකා",
          "ප.ව. 4 සිට රාත්‍රී 9 දක්වා අධීක්ෂිත විවෘත ප්‍රවේශය, සාමාජිකයින්ට සහ සිසුන්ට නොමිලේ",
        ],
        "## තත්ත්වය",
        "රු. මිලියන 2.1 ඉලක්කයෙන් රු. 420,000 රැස් කර ඇත. ප්‍රාදේශීය ව්‍යාපාරයක් වර්ෂ තුනක් සඳහා බිම් මහලේ ඉඩම කුලියකින් තොරව ලබා දීමට ඉදිරිපත් වී ඇති අතර, එය විශාලතම පුනරාවර්තන වියදම ඉවත් කරයි. ඉලක්කයෙන් 60% ලැබුණු විට ඉදිකිරීම් ආරම්භ වේ.",
        "## උදව් කරන ආකාරය",
        "අපට වර්ෂ පහකට නොවැඩි ප්‍රතිසංස්කරණය කළ පරිගණක, මොනිටර්, UPS එකක් සහ දෙමළ භාෂාවෙන් ඉගැන්විය හැකි ස්වේච්ඡා උපදේශකයින් දෙදෙනෙකු අවශ්‍යයි.",
      ]),
      ta: html([
        "கல்முனை இளைஞர்கள் தொலைநிலை சுயேச்சை வேலை — தரவு உள்ளிடல், எழுத்தாக்கம், வரைகலை வடிவமைப்பு — கண்டறிய முடிகிறது, ஆனால் அதைச் செய்ய நம்பகமான கணினியும் இணைப்பும் இல்லை. இந்த நிலையம் உள்ளூர் இளைஞர் சங்கத்தின் கோரிக்கைக்கு நேரடிப் பதில்.",
        "## திட்டமிடப்பட்ட வசதிகள்",
        [
          "ஃபைபர் இணைப்பும் காப்பு இன்வர்ட்டரும் கொண்ட பன்னிரண்டு புனரமைக்கப்பட்ட மேசைக் கணினிகள்",
          "அடக்க விலையில் பொது பயன்பாட்டுக்கு அச்சுப்பொறி, ஸ்கேனர், ஆவண நிலையம்",
          "இலவச மாலை வகுப்புகள்: அடிப்படைக் கணினி, விரிதாள், இணையவழி விற்பனை, சுயேச்சைத் தளங்கள்",
          "பி.ப. 4 முதல் இரவு 9 வரை மேற்பார்வையிடப்பட்ட திறந்த அணுகல், உறுப்பினர்களுக்கும் மாணவர்களுக்கும் இலவசம்",
        ],
        "## நிலை",
        "ரூ. 2.1 மில்லியன் இலக்கில் ரூ. 420,000 திரட்டப்பட்டுள்ளது. உள்ளூர் வணிகம் ஒன்று தரைத் தள இடத்தை மூன்று ஆண்டுகளுக்கு வாடகையின்றி வழங்க முன்வந்துள்ளது, இது மிகப்பெரிய தொடர் செலவை நீக்குகிறது. இலக்கின் 60% எட்டியதும் கட்டுமானம் தொடங்கும்.",
        "## உதவும் வழி",
        "ஐந்து ஆண்டுகளுக்கு மேற்படாத புனரமைக்கப்பட்ட கணினிகள், திரைகள், UPS, மற்றும் தமிழில் கற்பிக்கக்கூடிய இரு தொண்டர் பயிற்றுவிப்பாளர்கள் தேவை.",
      ]),
    },
  },
];
